# Generated by Django 5.2.8 on 2025-12-11 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría. Ej: Diezmo, Ofrenda, Electricidad.', max_length=100)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], help_text='Indica si la categoría es de ingreso o de egreso.', max_length=10)),
                ('es_editable', models.BooleanField(default=True, help_text='Si se desactiva, la categoría no se podrá borrar fácilmente.')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de movimiento',
                'verbose_name_plural': 'Categorías de movimientos',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la cuenta. Ej: Caja general, Banco Popular, etc.', max_length=100)),
                ('tipo', models.CharField(choices=[('caja', 'Caja'), ('banco', 'Banco'), ('otro', 'Otro')], default='caja', help_text='Tipo de cuenta (caja, banco u otro).', max_length=20)),
                ('moneda', models.CharField(default='DOP', help_text='Moneda principal de la cuenta. Ej: DOP, USD.', max_length=10)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, help_text='Saldo inicial de la cuenta al empezar a usar el sistema.', max_digits=12)),
                ('esta_activa', models.BooleanField(default=True, help_text='Permite activar o desactivar la cuenta sin borrarla.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta financiera',
                'verbose_name_plural': 'Cuentas financieras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha en la que se realizó el movimiento.')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], help_text='Si es un ingreso o un egreso.', max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del movimiento.', max_digits=12)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción breve o nota del movimiento.', max_length=255)),
                ('referencia', models.CharField(blank=True, help_text='Referencia opcional (nº recibo, nº factura, etc.).', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='Categoría del movimiento (diezmo, ofrenda, sueldo, etc.).', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas_app.categoriamovimiento')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que registró el movimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(help_text='Cuenta por donde entra o sale el dinero.', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='finanzas_app.cuentafinanciera')),
            ],
            options={
                'verbose_name': 'Movimiento financiero',
                'verbose_name_plural': 'Movimientos financieros',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
    ]
