# Generated by Django 5.2.8 on 2025-12-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriamovimiento',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name': 'Categoría de movimiento', 'verbose_name_plural': 'Categorías de movimiento'},
        ),
        migrations.RemoveField(
            model_name='categoriamovimiento',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='categoriamovimiento',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='cuentafinanciera',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='cuentafinanciera',
            name='creado_en',
        ),
        migrations.AddField(
            model_name='categoriamovimiento',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción opcional de la categoría.', max_length=255),
        ),
        migrations.AddField(
            model_name='cuentafinanciera',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción opcional de la cuenta.', max_length=255),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='cantidad_sobres',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de sobres recibidos (si aplica).', null=True),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cuadrado', 'Cuadrado'), ('anulado', 'Anulado')], default='confirmado', help_text='Estado interno del movimiento.', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='evento',
            field=models.CharField(blank=True, help_text='Nombre del evento o actividad. Ej: Noche de tacos, Campamento juvenil.', max_length=150),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque'), ('deposito', 'Depósito bancario'), ('otro', 'Otro')], help_text='Forma de pago utilizada.', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='ministerio',
            field=models.CharField(blank=True, help_text='Ministerio o departamento responsable. Ej: Jóvenes, Damas, Adolescentes.', max_length=150),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='origen',
            field=models.CharField(blank=True, choices=[('culto', 'Culto / servicio'), ('actividad', 'Actividad o evento'), ('donacion', 'Donación individual'), ('venta', 'Venta / recaudación'), ('ofrenda_especial', 'Ofrenda especial'), ('otro', 'Otro')], help_text='Origen principal del movimiento (culto, actividad, donación, etc.).', max_length=30),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='persona_asociada',
            field=models.CharField(blank=True, help_text='Nombre de la persona asociada al ingreso (si aplica).', max_length=150),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='servicio',
            field=models.CharField(blank=True, help_text='Nombre del culto o servicio. Ej: Domingo AM, Jueves enseñanza.', max_length=100),
        ),
        migrations.AlterField(
            model_name='categoriamovimiento',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si la categoría está disponible para usar.'),
        ),
        migrations.AlterField(
            model_name='categoriamovimiento',
            name='es_editable',
            field=models.BooleanField(default=True, help_text='Si la categoría puede ser editada/borrada desde el sistema.'),
        ),
        migrations.AlterField(
            model_name='categoriamovimiento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoriamovimiento',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], help_text='Si la categoría es de ingreso o de egreso.', max_length=10),
        ),
        migrations.AlterField(
            model_name='cuentafinanciera',
            name='esta_activa',
            field=models.BooleanField(default=True, help_text='Indica si la cuenta está activa.'),
        ),
        migrations.AlterField(
            model_name='cuentafinanciera',
            name='moneda',
            field=models.CharField(choices=[('DOP', 'Pesos dominicanos'), ('USD', 'Dólares estadounidenses'), ('EUR', 'Euros')], default='DOP', help_text='Moneda principal de la cuenta.', max_length=10),
        ),
        migrations.AlterField(
            model_name='cuentafinanciera',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cuentafinanciera',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo inicial de la cuenta.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cuentafinanciera',
            name='tipo',
            field=models.CharField(choices=[('caja', 'Caja'), ('banco', 'Banco'), ('otra', 'Otra')], help_text='Tipo de cuenta (caja, banco, otra).', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='referencia',
            field=models.CharField(blank=True, help_text='Referencia opcional (nº recibo, nº factura, nº transferencia, etc.).', max_length=100),
        ),
    ]
