# Generated by Django 5.2.8 on 2025-12-12 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0002_alter_categoriamovimiento_options_and_more'),
        ('miembros_app', '0012_miembro_codigo_miembro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='persona_asociada',
            field=models.ForeignKey(blank=True, help_text='Miembro asociado al movimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros', to='miembros_app.miembro'),
        ),
    ]
