# Generated by Django 5.2.8 on 2025-12-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0003_alter_movimientofinanciero_persona_asociada'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='es_transferencia',
            field=models.BooleanField(default=False, help_text='Indica si este movimiento es parte de una transferencia entre cuentas.'),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='transferencia_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='UUID compartido por ambos movimientos de una transferencia.', null=True),
        ),
    ]
