# Generated by Django - fecha actual

from django.db import migrations


def crear_categorias_transferencia(apps, schema_editor):
    """
    Crea las categorías especiales para transferencias.
    """
    CategoriaMovimiento = apps.get_model('finanzas_app', 'CategoriaMovimiento')
    
    # Categoría para el lado del ENVÍO (egreso)
    CategoriaMovimiento.objects.get_or_create(
        nombre="Transferencia enviada",
        defaults={
            'tipo': 'egreso',
            'descripcion': 'Categoría automática para transferencias entre cuentas (salida).',
            'activo': True,
            'es_editable': False,  # No debe poder borrarse
        }
    )
    
    # Categoría para el lado de la RECEPCIÓN (ingreso)
    CategoriaMovimiento.objects.get_or_create(
        nombre="Transferencia recibida",
        defaults={
            'tipo': 'ingreso',
            'descripcion': 'Categoría automática para transferencias entre cuentas (entrada).',
            'activo': True,
            'es_editable': False,  # No debe poder borrarse
        }
    )


def eliminar_categorias_transferencia(apps, schema_editor):
    """
    Elimina las categorías de transferencia (rollback).
    """
    CategoriaMovimiento = apps.get_model('finanzas_app', 'CategoriaMovimiento')
    
    CategoriaMovimiento.objects.filter(
        nombre__in=['Transferencia enviada', 'Transferencia recibida']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0004_movimientofinanciero_es_transferencia_and_more'),  # 👈 Ajusta este número según tu migración anterior
    ]

    operations = [
        migrations.RunPython(
            crear_categorias_transferencia,
            eliminar_categorias_transferencia
        ),
    ]