# Generated by Django 5.2.8 on 2025-12-12 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0005_auto_20251212_1455'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo adjunto.', upload_to='finanzas/adjuntos/%Y/%m/')),
                ('nombre_original', models.CharField(help_text='Nombre original del archivo.', max_length=255)),
                ('tamaño', models.PositiveIntegerField(help_text='Tamaño del archivo en bytes.')),
                ('tipo_mime', models.CharField(blank=True, help_text='Tipo MIME del archivo (image/jpeg, application/pdf, etc.).', max_length=100)),
                ('subido_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de subida.')),
                ('movimiento', models.ForeignKey(help_text='Movimiento al que pertenece este adjunto.', on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='finanzas_app.movimientofinanciero')),
                ('subido_por', models.ForeignKey(blank=True, help_text='Usuario que subió el archivo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto de movimiento',
                'verbose_name_plural': 'Adjuntos de movimientos',
                'ordering': ['-subido_en'],
            },
        ),
    ]
