# Generated by Django 5.2.8 on 2025-12-13 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0006_adjuntomovimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='anulado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se anuló el movimiento.', null=True),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='anulado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que anuló el movimiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='motivo_anulacion',
            field=models.TextField(blank=True, help_text='Motivo o comentario de por qué se anuló el movimiento.'),
        ),
    ]
