# Generated by Django 5.2.8 on 2026-01-10 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0015_movimientounidad_actualizado_por_movimientounidadlog'),
        ('finanzas_app', '0007_movimientofinanciero_anulado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='unidad',
            field=models.ForeignKey(blank=True, help_text='Unidad de Estructura asociada (si el módulo Estructura está activo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros', to='estructura_app.unidad'),
        ),
    ]
