# Generated by Django 5.2.8 on 2026-01-18 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0008_movimientofinanciero_unidad'),
        ('miembros_app', '0032_miembro_padres_espirituales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('persona', 'Persona'), ('empresa', 'Empresa')], default='persona', max_length=10)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('miembro', models.ForeignKey(blank=True, help_text='Si este proveedor coincide con un miembro, puedes enlazarlo (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedor_financiero', to='miembros_app.miembro')),
            ],
            options={
                'verbose_name': 'Proveedor financiero',
                'verbose_name_plural': 'Proveedores financieros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('referencia', models.CharField(blank=True, help_text='Nº factura, recibo, contrato, etc. (opcional).', max_length=100)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(help_text='Categoría de egreso para reportes (luz, alquiler, honorarios, etc.).', limit_choices_to={'tipo': 'egreso'}, on_delete=django.db.models.deletion.PROTECT, related_name='cxp', to='finanzas_app.categoriamovimiento')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxp_creadas', to=settings.AUTH_USER_MODEL)),
                ('cuenta_sugerida', models.ForeignKey(blank=True, help_text='Cuenta desde la que normalmente se pagará (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cxp_sugeridas', to='finanzas_app.cuentafinanciera')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar', to='finanzas_app.proveedorfinanciero')),
            ],
            options={
                'verbose_name': 'Cuenta por pagar',
                'verbose_name_plural': 'Cuentas por pagar',
                'ordering': ['-fecha_emision', '-creado_en'],
                'indexes': [models.Index(fields=['estado', 'fecha_vencimiento'], name='finanzas_ap_estado_f3f352_idx'), models.Index(fields=['fecha_emision'], name='finanzas_ap_fecha_e_9cb6b0_idx')],
            },
        ),
    ]
