# Generated by Django 5.2.8 on 2026-01-18 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0009_proveedorfinanciero_cuentaporpagar'),
        ('miembros_app', '0032_miembro_padres_espirituales'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorfinanciero',
            name='banco',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='proveedorfinanciero',
            name='bloqueado',
            field=models.BooleanField(default=False, help_text='Si está bloqueado, no se deben permitir nuevas CxP para este proveedor.'),
        ),
        migrations.AddField(
            model_name='proveedorfinanciero',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proveedorfinanciero',
            name='documento',
            field=models.CharField(blank=True, help_text='RNC/Cédula/Pasaporte. Guardar sin guiones (solo números cuando aplique).', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='proveedorfinanciero',
            name='metodo_pago_preferido',
            field=models.CharField(blank=True, choices=[('', '—'), ('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='proveedorfinanciero',
            name='numero_cuenta',
            field=models.CharField(blank=True, help_text='Número de cuenta (texto, puede incluir ceros iniciales).', max_length=34),
        ),
        migrations.AddField(
            model_name='proveedorfinanciero',
            name='plazo_dias_pago',
            field=models.PositiveIntegerField(default=30, help_text='Días de crédito para calcular vencimiento si la factura no trae fecha.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='proveedorfinanciero',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('', '—'), ('ahorros', 'Ahorros'), ('corriente', 'Corriente')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='proveedorfinanciero',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('', '—'), ('cedula', 'Cédula'), ('rnc', 'RNC'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='proveedorfinanciero',
            name='tipo_proveedor',
            field=models.CharField(choices=[('servicio', 'Servicio'), ('consumibles', 'Consumibles'), ('mixto', 'Mixto')], default='servicio', help_text='Clasificación: servicio o consumibles.', max_length=12),
        ),
        migrations.AddField(
            model_name='proveedorfinanciero',
            name='titular_cuenta',
            field=models.CharField(blank=True, help_text='Titular de la cuenta si difiere del proveedor (opcional).', max_length=150),
        ),
        migrations.AddConstraint(
            model_name='proveedorfinanciero',
            constraint=models.UniqueConstraint(condition=models.Q(('documento__isnull', False)), fields=('tipo_documento', 'documento'), name='uq_proveedor_tipo_doc_documento'),
        ),
    ]
