# Generated by Django 5.2.8 on 2026-01-19 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0010_proveedorfinanciero_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='cuenta_por_pagar',
            field=models.ForeignKey(blank=True, help_text='Si este egreso es un pago de CxP, referencia a la cuenta por pagar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='finanzas_app.cuentaporpagar'),
        ),
    ]
