# Generated by Django 5.2.8 on 2026-01-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0011_movimientofinanciero_cuenta_por_pagar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientofinanciero',
            options={'ordering': ['-fecha', '-creado_en'], 'permissions': [('ver_dashboard_finanzas', 'Puede ver el Dashboard de Finanzas')], 'verbose_name': 'Movimiento financiero', 'verbose_name_plural': 'Movimientos financieros'},
        ),
    ]
