# Generated by Django 5.2.8 on 2026-02-15 21:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0012_alter_movimientofinanciero_options'),
        ('miembros_app', '0036_miembrorelacion_es_inferida'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proveedorfinanciero',
            name='uq_proveedor_tipo_doc_documento',
        ),
        migrations.AlterField(
            model_name='cuentafinanciera',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo inicial de la cuenta.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto del movimiento.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='categoriamovimiento',
            constraint=models.UniqueConstraint(fields=('nombre', 'tipo'), name='uq_categoria_nombre_tipo'),
        ),
        migrations.AddConstraint(
            model_name='cuentafinanciera',
            constraint=models.UniqueConstraint(fields=('nombre',), name='uq_cuenta_financiera_nombre'),
        ),
        migrations.AddConstraint(
            model_name='proveedorfinanciero',
            constraint=models.UniqueConstraint(condition=models.Q(('documento__isnull', False), models.Q(('documento', ''), _negated=True)), fields=('tipo_documento', 'documento'), name='uq_proveedor_tipo_doc_documento'),
        ),
        migrations.AddConstraint(
            model_name='proveedorfinanciero',
            constraint=models.UniqueConstraint(fields=('nombre',), name='uq_proveedor_nombre'),
        ),
    ]
