# Generated by Django 5.2.8 on 2026-02-15 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0013_remove_proveedorfinanciero_uq_proveedor_tipo_doc_documento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasillaF001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código interno estable. Ej: ING_DIEZMOS, MIN_FEMENIL, EGR_SERVICIOS', max_length=60, unique=True)),
                ('nombre', models.CharField(help_text='Nombre visible en Admin. Ej: Diezmos, Ministerio Femenil, Agua/Luz/Teléfono', max_length=120)),
                ('seccion', models.CharField(choices=[('ingresos_iglesia', 'Ingresos Generales de la Iglesia'), ('ingresos_ministerios', 'Ingresos de los Ministerios'), ('egresos', 'Egresos de la Iglesia')], help_text='Sección del F.001 donde aparece esta casilla.', max_length=30)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición (opcional).')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo para usarse en categorías.')),
            ],
            options={
                'verbose_name': 'Casilla F.001',
                'verbose_name_plural': 'Casillas F.001',
                'ordering': ['seccion', 'orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='categoriamovimiento',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código interno estable. Ej: CAT_DIEZMO_NO_REGULAR. Recomendado.', max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categoriamovimiento',
            name='casilla_f001',
            field=models.ForeignKey(blank=True, help_text='Opcional. Si se asigna, esta categoría alimenta el Informe F.001.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='finanzas_app.casillaf001'),
        ),
    ]
