# Generated by Django 5.2.8 on 2026-02-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0015_seed_f001_casillas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casillaf001',
            name='seccion',
            field=models.CharField(choices=[('ingresos_iglesia', 'Ingresos Generales de la Iglesia'), ('ingresos_ministerios', 'Ingresos de los Ministerios'), ('egresos', 'Egresos de la Iglesia'), ('envios_ministerios', 'Envíos a Ministerios Nacionales'), ('aportes_especiales', 'Aportes Especiales')], help_text='Sección del F.001 donde aparece esta casilla.', max_length=30),
        ),
    ]
