# Generated by Django 5.2.8 on 2026-03-04 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_app', '0016_alter_casillaf001_seccion'),
        ('miembros_app', '0040_miembrorelacion_unique_relacion_por_tenant'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categoriamovimiento',
            name='uq_categoria_nombre_tipo',
        ),
        migrations.RemoveConstraint(
            model_name='cuentafinanciera',
            name='uq_cuenta_financiera_nombre',
        ),
        migrations.RemoveConstraint(
            model_name='proveedorfinanciero',
            name='uq_proveedor_tipo_doc_documento',
        ),
        migrations.RemoveConstraint(
            model_name='proveedorfinanciero',
            name='uq_proveedor_nombre',
        ),
        migrations.AddField(
            model_name='categoriamovimiento',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentafinanciera',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedorfinanciero',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriamovimiento',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código interno estable. Ej: CAT_DIEZMO_NO_REGULAR. Recomendado.', max_length=60, null=True),
        ),
        migrations.AddConstraint(
            model_name='categoriamovimiento',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre', 'tipo'), name='uq_categoria_nombre_tipo_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='categoriamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo__isnull', False), models.Q(('codigo', ''), _negated=True)), fields=('tenant', 'codigo'), name='uq_categoria_codigo_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='cuentafinanciera',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='uq_cuenta_financiera_nombre_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='proveedorfinanciero',
            constraint=models.UniqueConstraint(condition=models.Q(('documento__isnull', False), models.Q(('documento', ''), _negated=True)), fields=('tenant', 'tipo_documento', 'documento'), name='uq_proveedor_tipo_doc_documento_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='proveedorfinanciero',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='uq_proveedor_nombre_por_tenant'),
        ),
    ]
