# Generated by Django 5.2.8 on 2026-01-27 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estructura_app', '0017_unidad_hereda_liderazgo'),
        ('miembros_app', '0036_miembrorelacion_es_inferida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.PositiveSmallIntegerField(choices=[(1, 'Rojo'), (2, 'Amarillo'), (3, 'Verde')])),
                ('participacion', models.PositiveSmallIntegerField(choices=[(1, 'Rojo'), (2, 'Amarillo'), (3, 'Verde')])),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Rojo'), (2, 'Amarillo'), (3, 'Verde')])),
                ('puntaje_total', models.PositiveSmallIntegerField(default=0)),
                ('estrellas', models.PositiveSmallIntegerField(default=0)),
                ('nota', models.CharField(blank=True, max_length=280)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('evaluador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='miembros_app.miembro')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_miembros', to='estructura_app.unidad')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['unidad', 'miembro', '-creado_en'], name='evaluacione_unidad__9a8fac_idx'), models.Index(fields=['evaluador', '-creado_en'], name='evaluacione_evaluad_d08dcc_idx')],
            },
        ),
    ]
