# Generated by Django 5.2.8 on 2026-01-27 15:32

import django.db.models.deletion
import evaluaciones_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0017_unidad_hereda_liderazgo'),
        ('evaluaciones_app', '0001_initial'),
        ('miembros_app', '0036_miembrorelacion_es_inferida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(default=evaluaciones_app.models.current_year)),
                ('mes', models.PositiveSmallIntegerField(default=evaluaciones_app.models.current_month)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_PROGRESO', 'En progreso'), ('CERRADA', 'Cerrada')], default='BORRADOR', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evaluación de unidad',
                'verbose_name_plural': 'Evaluaciones de unidad',
                'ordering': ['-anio', '-mes', 'unidad__nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='evaluacionmiembro',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Evaluación de miembro', 'verbose_name_plural': 'Evaluaciones de miembros'},
        ),
        migrations.RemoveIndex(
            model_name='evaluacionmiembro',
            name='evaluacione_unidad__9a8fac_idx',
        ),
        migrations.RemoveIndex(
            model_name='evaluacionmiembro',
            name='evaluacione_evaluad_d08dcc_idx',
        ),
        migrations.RemoveField(
            model_name='evaluacionmiembro',
            name='estrellas',
        ),
        migrations.RemoveField(
            model_name='evaluacionmiembro',
            name='evaluador',
        ),
        migrations.RemoveField(
            model_name='evaluacionmiembro',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='evaluacionmiembro',
            name='puntaje_total',
        ),
        migrations.RemoveField(
            model_name='evaluacionmiembro',
            name='unidad',
        ),
        migrations.AddField(
            model_name='evaluacionmiembro',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='evaluacionmiembro',
            name='evaluado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_miembro_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluacionmiembro',
            name='observacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='evaluacionmiembro',
            name='puntaje_general',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AlterField(
            model_name='evaluacionmiembro',
            name='asistencia',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AlterField(
            model_name='evaluacionmiembro',
            name='estado',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('EN_RIESGO', 'En riesgo'), ('AUSENTE', 'Ausente')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='evaluacionmiembro',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='miembros_app.miembro'),
        ),
        migrations.AlterField(
            model_name='evaluacionmiembro',
            name='participacion',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AddField(
            model_name='evaluacionunidad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_unidad_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluacionunidad',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='estructura_app.unidad'),
        ),
        migrations.AddField(
            model_name='evaluacionmiembro',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evaluaciones_app.evaluacionunidad'),
        ),
        migrations.AddIndex(
            model_name='evaluacionmiembro',
            index=models.Index(fields=['evaluacion'], name='evaluacione_evaluac_04eb72_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionmiembro',
            index=models.Index(fields=['miembro'], name='evaluacione_miembro_c82e11_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionmiembro',
            index=models.Index(fields=['estado'], name='evaluacione_estado_2237d3_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionmiembro',
            index=models.Index(fields=['puntaje_general'], name='evaluacione_puntaje_ae2893_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluacionmiembro',
            constraint=models.UniqueConstraint(fields=('evaluacion', 'miembro'), name='uniq_evaluacion_miembro_por_periodo'),
        ),
        migrations.AddIndex(
            model_name='evaluacionunidad',
            index=models.Index(fields=['unidad', 'anio', 'mes'], name='evaluacione_unidad__7844de_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionunidad',
            index=models.Index(fields=['estado'], name='evaluacione_estado_f05d66_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluacionunidad',
            constraint=models.UniqueConstraint(fields=('unidad', 'anio', 'mes'), name='uniq_evaluacion_unidad_anio_mes'),
        ),
    ]
