# Generated by Django 5.2.8 on 2026-01-27 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_app', '0002_evaluacionunidad_alter_evaluacionmiembro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionunidad',
            name='asistencia',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='evaluacionunidad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionunidad',
            name='participacion',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='evaluacionunidad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
