# Generated by Django 5.2.8 on 2026-01-27 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0017_unidad_hereda_liderazgo'),
        ('evaluaciones_app', '0003_evaluacionunidad_asistencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='evaluacionunidad',
            name='evaluacione_estado_f05d66_idx',
        ),
        migrations.RenameField(
            model_name='evaluacionunidad',
            old_name='estado',
            new_name='estado_workflow',
        ),
        migrations.RemoveField(
            model_name='evaluacionunidad',
            name='asistencia',
        ),
        migrations.RemoveField(
            model_name='evaluacionunidad',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='evaluacionunidad',
            name='participacion',
        ),
        migrations.RemoveField(
            model_name='evaluacionunidad',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='evaluacionunidad',
            name='diagnostico',
            field=models.CharField(choices=[('estable', 'Estable'), ('crecimiento', 'En crecimiento'), ('irregular', 'Asistencia irregular'), ('observacion', 'En observación'), ('seguimiento', 'En seguimiento'), ('riesgo', 'En riesgo'), ('inactivo', 'Inactivo')], default='estable', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluacionunidad',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacionunidad',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_unidad', to='estructura_app.unidad'),
        ),
        migrations.AddIndex(
            model_name='evaluacionunidad',
            index=models.Index(fields=['estado_workflow'], name='evaluacione_estado__b44f09_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacionunidad',
            index=models.Index(fields=['diagnostico'], name='evaluacione_diagnos_40bc18_idx'),
        ),
    ]
