# Generated by Django 5.2.8 on 2026-01-27 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0017_unidad_hereda_liderazgo'),
        ('evaluaciones_app', '0004_remove_evaluacionunidad_evaluacione_estado_f05d66_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionPerfilUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('LIBRE', 'Libre')], default='MENSUAL', max_length=10)),
                ('w_asistencia', models.DecimalField(decimal_places=2, default=0.2, max_digits=4)),
                ('w_participacion', models.DecimalField(decimal_places=2, default=0.2, max_digits=4)),
                ('w_compromiso', models.DecimalField(decimal_places=2, default=0.2, max_digits=4)),
                ('w_actitud', models.DecimalField(decimal_places=2, default=0.15, max_digits=4)),
                ('w_integracion', models.DecimalField(decimal_places=2, default=0.15, max_digits=4)),
                ('w_liderazgo', models.DecimalField(decimal_places=2, default=0.1, max_digits=4)),
                ('excluir_evaluador', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('unidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_evaluacion', to='estructura_app.unidad')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacionunidad',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluaciones_app.evaluacionperfilunidad'),
        ),
    ]
