# Generated by Django 5.2.8 on 2026-01-28 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_app', '0005_evaluacionperfilunidad_evaluacionunidad_perfil'),
        ('miembros_app', '0036_miembrorelacion_es_inferida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='evaluacionmiembro',
            name='evaluacione_estado_2237d3_idx',
        ),
        migrations.RemoveField(
            model_name='evaluacionmiembro',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='evaluacionperfilunidad',
            name='w_liderazgo',
        ),
        migrations.AddField(
            model_name='evaluacionmiembro',
            name='actitud',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AddField(
            model_name='evaluacionmiembro',
            name='compromiso',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AddField(
            model_name='evaluacionmiembro',
            name='estado_espiritual',
            field=models.CharField(choices=[('ESTABLE', '🟢 Estable'), ('EN_CRECIMIENTO', '🌱 En crecimiento'), ('EN_PROCESO', '🧩 En proceso'), ('INESTABLE', '🌊 Inestable'), ('EN_RIESGO', '⚠️ En riesgo'), ('CRITICO', '🔴 Crítico'), ('AUSENTE', '⚫ Ausente')], default='ESTABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluacionmiembro',
            name='integracion',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AddField(
            model_name='evaluacionmiembro',
            name='madurez_espiritual',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AddField(
            model_name='evaluacionperfilunidad',
            name='w_madurez_espiritual',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='evaluacionperfilunidad',
            name='w_actitud',
            field=models.DecimalField(decimal_places=2, default=0.13, max_digits=4),
        ),
        migrations.AlterField(
            model_name='evaluacionperfilunidad',
            name='w_asistencia',
            field=models.DecimalField(decimal_places=2, default=0.18, max_digits=4),
        ),
        migrations.AlterField(
            model_name='evaluacionperfilunidad',
            name='w_compromiso',
            field=models.DecimalField(decimal_places=2, default=0.18, max_digits=4),
        ),
        migrations.AlterField(
            model_name='evaluacionperfilunidad',
            name='w_integracion',
            field=models.DecimalField(decimal_places=2, default=0.13, max_digits=4),
        ),
        migrations.AlterField(
            model_name='evaluacionperfilunidad',
            name='w_participacion',
            field=models.DecimalField(decimal_places=2, default=0.18, max_digits=4),
        ),
        migrations.AddIndex(
            model_name='evaluacionmiembro',
            index=models.Index(fields=['estado_espiritual'], name='evaluacione_estado__7ce077_idx'),
        ),
    ]
