# Generated by Django 5.2.8 on 2026-01-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_app', '0006_remove_evaluacionmiembro_evaluacione_estado_2237d3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionperfilunidad',
            name='auto_crear_periodo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluacionperfilunidad',
            name='dia_cierre',
            field=models.PositiveSmallIntegerField(default=28),
        ),
        migrations.AddField(
            model_name='evaluacionperfilunidad',
            name='frecuencia',
            field=models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual'), ('LIBRE', 'Libre')], default='MENSUAL', max_length=12),
        ),
        migrations.AddField(
            model_name='evaluacionperfilunidad',
            name='permitir_editar_cerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluacionperfilunidad',
            name='usar_actitud',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluacionperfilunidad',
            name='usar_asistencia',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluacionperfilunidad',
            name='usar_compromiso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluacionperfilunidad',
            name='usar_estado_espiritual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluacionperfilunidad',
            name='usar_integracion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluacionperfilunidad',
            name='usar_madurez_espiritual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluacionperfilunidad',
            name='usar_participacion',
            field=models.BooleanField(default=True),
        ),
    ]
