# Generated by Django 5.2.8 on 2026-01-28 00:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_app', '0007_evaluacionperfilunidad_auto_crear_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionperfilunidad',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
