# Generated by Django 5.2.8 on 2026-01-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_app', '0008_evaluacionperfilunidad_creado_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionperfilunidad',
            name='usar_liderazgo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluacionperfilunidad',
            name='w_liderazgo',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=4),
        ),
    ]
