# Generated by Django 5.2.8 on 2026-01-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_app', '0009_evaluacionperfilunidad_usar_liderazgo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionperfilunidad',
            name='w_actitud',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='evaluacionperfilunidad',
            name='w_asistencia',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='evaluacionperfilunidad',
            name='w_compromiso',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='evaluacionperfilunidad',
            name='w_integracion',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='evaluacionperfilunidad',
            name='w_liderazgo',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='evaluacionperfilunidad',
            name='w_madurez_espiritual',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='evaluacionperfilunidad',
            name='w_participacion',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
