# Generated by Django 5.2.8 on 2026-01-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_app', '0010_alter_evaluacionperfilunidad_w_actitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionperfilunidad',
            name='usar_pesos',
            field=models.BooleanField(default=False),
        ),
    ]
