# Generated by Django 5.2.8 on 2026-01-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_app', '0011_evaluacionperfilunidad_usar_pesos'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionmiembro',
            name='liderazgo',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
