# Generated by Django 5.2.8 on 2026-01-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_app', '0012_evaluacionmiembro_liderazgo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacionperfilunidad',
            options={'verbose_name': 'Perfil de evaluación', 'verbose_name_plural': 'Perfiles de evaluación'},
        ),
        migrations.RemoveField(
            model_name='evaluacionperfilunidad',
            name='auto_crear_periodo',
        ),
        migrations.AlterField(
            model_name='evaluacionperfilunidad',
            name='dia_cierre',
            field=models.PositiveSmallIntegerField(default=28, help_text='Día del mes para cerrar evaluaciones (1-28).'),
        ),
        migrations.AlterField(
            model_name='evaluacionperfilunidad',
            name='frecuencia',
            field=models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSUAL', help_text='Solo aplica en modo Automático.', max_length=12),
        ),
        migrations.AlterField(
            model_name='evaluacionperfilunidad',
            name='modo',
            field=models.CharField(choices=[('AUTO', 'Automático'), ('LIBRE', 'Libre')], default='AUTO', help_text='AUTO: crea períodos según frecuencia. LIBRE: el líder crea cuando quiera.', max_length=10),
        ),
    ]
