# Generated by Django 5.2.8 on 2026-01-29 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0017_unidad_hereda_liderazgo'),
        ('evaluaciones_app', '0013_alter_evaluacionperfilunidad_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evaluacionunidad',
            name='uniq_evaluacion_unidad_anio_mes',
        ),
        migrations.AddField(
            model_name='evaluacionunidad',
            name='numero_secuencia',
            field=models.PositiveSmallIntegerField(default=1, help_text='Secuencia para múltiples evaluaciones en modo libre (1, 2, 3...)'),
        ),
        migrations.AddConstraint(
            model_name='evaluacionunidad',
            constraint=models.UniqueConstraint(fields=('unidad', 'anio', 'mes', 'numero_secuencia'), name='uniq_evaluacion_unidad_periodo_secuencia'),
        ),
    ]
