# Generated by Django 5.2.8 on 2025-12-31 18:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miembros_app', '0013_miembro_codigo_seguimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoCreyenteExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_SEGUIMIENTO', 'En seguimiento'), ('CERRADO', 'Cerrado')], db_index=True, default='EN_SEGUIMIENTO', max_length=20)),
                ('fecha_envio', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('proximo_contacto', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('miembro', models.OneToOneField(help_text='Miembro enviado al módulo de Nuevo Creyente.', on_delete=django.db.models.deletion.CASCADE, related_name='expediente_nuevo_creyente', to='miembros_app.miembro')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_nuevo_creyente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expediente (Nuevo Creyente)',
                'verbose_name_plural': 'Expedientes (Nuevo Creyente)',
                'ordering': ['-fecha_envio', '-fecha_creacion'],
            },
        ),
    ]
