# Generated by Django 5.2.8 on 2026-01-02 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0013_miembro_codigo_seguimiento_and_more'),
        ('nuevo_creyente_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoCreyentePadreEspiritual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padres_links', to='nuevo_creyente_app.nuevocreyenteexpediente')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuevo_creyente_padrino_links', to='miembros_app.miembro')),
            ],
            options={
                'unique_together': {('expediente', 'padre')},
            },
        ),
        migrations.AddField(
            model_name='nuevocreyenteexpediente',
            name='padres_espirituales',
            field=models.ManyToManyField(blank=True, related_name='expedientes_nuevo_creyente_padrinos', through='nuevo_creyente_app.NuevoCreyentePadreEspiritual', to='miembros_app.miembro'),
        ),
    ]
