# Generated by Django 5.2.8 on 2026-01-02 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0013_reporteunidadcierre'),
        ('nuevo_creyente_app', '0002_nuevocreyentepadreespiritual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevocreyenteexpediente',
            name='unidad_responsable',
            field=models.ForeignKey(blank=True, help_text='Unidad responsable del seguimiento del nuevo creyente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_nuevo_creyente', to='estructura_app.unidad'),
        ),
    ]
