# Generated by Django 5.2.8 on 2026-01-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_creyente_app', '0003_nuevocreyenteexpediente_unidad_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevocreyenteexpediente',
            name='etapa',
            field=models.CharField(choices=[('INICIO', 'Inicio'), ('PRIMER_CONTACTO', 'Primer contacto'), ('ACOMPANAMIENTO', 'Acompañamiento'), ('INTEGRACION', 'Integración'), ('EVALUACION', 'Evaluación'), ('CIERRE', 'Cierre')], db_index=True, default='INICIO', help_text='Etapa actual del ciclo de seguimiento (manual asistido).', max_length=30),
        ),
    ]
