# Generated by Django 5.2.8 on 2026-01-02 16:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_creyente_app', '0004_nuevocreyenteexpediente_etapa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoCreyenteBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sistema', 'Sistema'), ('contacto', 'Contacto'), ('etapa', 'Cambio de etapa'), ('padre', 'Padre espiritual'), ('nota', 'Nota'), ('cierre', 'Cierre')], default='sistema', max_length=20)),
                ('titulo', models.CharField(max_length=120)),
                ('detalle', models.TextField(blank=True, default='')),
                ('canal', models.CharField(blank=True, choices=[('llamada', 'Llamada'), ('whatsapp', 'WhatsApp'), ('presencial', 'Presencial'), ('referido', 'Familiar / Referido'), ('otro', 'Otro')], default='', max_length=20)),
                ('resultado_contacto', models.CharField(blank=True, choices=[('contactado', 'Contactado'), ('no_responde', 'No respondió'), ('num_err', 'Número incorrecto'), ('pendiente', 'Pendiente (acordado luego)')], default='', max_length=20)),
                ('etapa_from', models.CharField(blank=True, default='', max_length=30)),
                ('etapa_to', models.CharField(blank=True, default='', max_length=30)),
                ('padre_miembro_id', models.IntegerField(blank=True, null=True)),
                ('padre_nombre', models.CharField(blank=True, default='', max_length=120)),
                ('padre_accion', models.CharField(blank=True, default='', max_length=20)),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_bitacoras', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='nuevo_creyente_app.nuevocreyenteexpediente')),
            ],
            options={
                'verbose_name': 'Bitácora Nuevo Creyente',
                'verbose_name_plural': 'Bitácoras Nuevo Creyente',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
