# Generated by Django 5.2.8 on 2026-01-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevo_creyente_app', '0005_nuevocreyentebitacora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevocreyentebitacora',
            name='tipo',
            field=models.CharField(choices=[('sistema', 'Sistema'), ('contacto', 'Contacto'), ('acompanamiento', 'Acompañamiento'), ('evaluacion', 'Evaluación'), ('integracion', 'Integración'), ('etapa', 'Cambio de etapa'), ('padre', 'Padre espiritual'), ('nota', 'Nota'), ('cierre', 'Cierre')], default='sistema', max_length=20),
        ),
    ]
