# Generated by Django 5.2.8 on 2026-02-03 15:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciclo de programa',
                'verbose_name_plural': 'Ciclos de programa',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('CONTINUO', 'Continuo'), ('POR_CICLO', 'Por ciclo')], default='POR_CICLO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Programa educativo',
                'verbose_name_plural': 'Programas educativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GrupoFormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('sexo_permitido', models.CharField(choices=[('VARONES', 'Varones'), ('HEMBRAS', 'Hembras'), ('MIXTO', 'Mixto')], default='MIXTO', max_length=10)),
                ('edad_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('edad_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=120)),
                ('lugar', models.CharField(blank=True, max_length=120)),
                ('cupo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='formacion_app.cicloprograma')),
                ('maestro', models.ForeignKey(blank=True, help_text='Usuario maestro/facilitador responsable (por ahora User).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_formacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo formativo',
                'verbose_name_plural': 'Grupos formativos',
                'ordering': ['nombre'],
                'unique_together': {('ciclo', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='cicloprograma',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos', to='formacion_app.programaeducativo'),
        ),
        migrations.CreateModel(
            name='InscripcionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miembro_id', models.PositiveIntegerField(help_text='ID del Miembro (temporal).')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETIRADO', 'Retirado'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=12)),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.now)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='formacion_app.grupoformativo')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('miembro_id', 'grupo'), name='uniq_miembro_grupo')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cicloprograma',
            unique_together={('programa', 'nombre')},
        ),
    ]
