# Generated by Django 5.2.8 on 2026-02-04 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grupoformativo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grupoformativo',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupoformativo',
            name='programa',
            field=models.ForeignKey(blank=True, help_text='Programa educativo al que pertenece (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='formacion_app.programaeducativo'),
        ),
        migrations.AlterField(
            model_name='grupoformativo',
            name='ciclo',
            field=models.ForeignKey(blank=True, help_text='Ciclo del programa (opcional, no usado por ahora).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='formacion_app.cicloprograma'),
        ),
        migrations.AlterField(
            model_name='grupoformativo',
            name='maestro',
            field=models.ForeignKey(blank=True, help_text='Usuario responsable del grupo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_formativos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='grupoformativo',
            unique_together={('programa', 'nombre')},
        ),
    ]
