# Generated by Django 5.2.8 on 2026-02-04 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_app', '0002_alter_grupoformativo_unique_together_and_more'),
        ('miembros_app', '0036_miembrorelacion_es_inferida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inscripciongrupo',
            name='uniq_miembro_grupo',
        ),
        migrations.RemoveField(
            model_name='inscripciongrupo',
            name='miembro_id',
        ),
        migrations.AddField(
            model_name='grupoformativo',
            name='ayudantes',
            field=models.ManyToManyField(blank=True, help_text='Ayudantes del grupo.', related_name='grupos_como_ayudante', to='miembros_app.miembro'),
        ),
        migrations.AddField(
            model_name='grupoformativo',
            name='maestros',
            field=models.ManyToManyField(blank=True, help_text='Maestros responsables del grupo.', related_name='grupos_como_maestro', to='miembros_app.miembro'),
        ),
        migrations.AddField(
            model_name='inscripciongrupo',
            name='miembro',
            field=models.ForeignKey(default=None, help_text='Miembro inscrito en el grupo.', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_formacion', to='miembros_app.miembro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupoformativo',
            name='ciclo',
            field=models.ForeignKey(blank=True, help_text='Ciclo del programa (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='formacion_app.cicloprograma'),
        ),
        migrations.AlterField(
            model_name='grupoformativo',
            name='maestro',
            field=models.ForeignKey(blank=True, help_text='(Legacy) Usuario responsable del grupo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_formativos_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='inscripciongrupo',
            constraint=models.UniqueConstraint(fields=('miembro', 'grupo'), name='uniq_miembro_grupo'),
        ),
    ]
