# Generated by Django 5.2.8 on 2026-02-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_app', '0003_remove_inscripciongrupo_uniq_miembro_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoformativo',
            name='estado_civil_permitido',
            field=models.CharField(choices=[('TODOS', 'Todos'), ('SOLTERO', 'Solteros'), ('CASADO', 'Casados'), ('VIUDO', 'Viudos'), ('DIVORCIADO', 'Divorciados')], default='TODOS', help_text='Filtro por estado civil para sugerencias de alumnos.', max_length=15),
        ),
    ]
