# Generated by Django 5.2.8 on 2026-02-05 19:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_app', '0004_grupoformativo_estado_civil_permitido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_grupo_creadas', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='formacion_app.grupoformativo')),
            ],
            options={
                'ordering': ['-inicio'],
                'indexes': [models.Index(fields=['grupo', 'estado', 'fecha'], name='formacion_a_grupo_i_fa8c48_idx')],
            },
        ),
    ]
