# Generated by Django 5.2.8 on 2026-02-05 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_app', '0005_sesiongrupo'),
        ('miembros_app', '0036_miembrorelacion_es_inferida'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcado_en', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(choices=[('QR', 'QR'), ('KIOSKO', 'Kiosko'), ('MANUAL', 'Manual')], default='KIOSKO', max_length=10)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_formacion', to='miembros_app.miembro')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='formacion_app.sesiongrupo')),
            ],
            options={
                'ordering': ['-marcado_en'],
                'constraints': [models.UniqueConstraint(fields=('sesion', 'miembro'), name='uniq_asistencia_por_sesion')],
            },
        ),
    ]
