# Generated by Django 5.2.8 on 2026-02-05 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacion_app', '0006_asistenciasesion'),
        ('miembros_app', '0036_miembrorelacion_es_inferida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolFormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MAESTRO', 'Maestro'), ('AYUDANTE', 'Ayudante')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol formativo',
                'verbose_name_plural': 'Roles formativos',
                'ordering': ['tipo', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='sesiongrupo',
            constraint=models.UniqueConstraint(fields=('grupo', 'fecha'), name='uniq_sesion_grupo_fecha'),
        ),
        migrations.AddField(
            model_name='rolformativo',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_formativos', to='miembros_app.miembro'),
        ),
        migrations.AddConstraint(
            model_name='rolformativo',
            constraint=models.UniqueConstraint(fields=('miembro', 'tipo'), name='uniq_rol_formativo_por_miembro'),
        ),
    ]
