# Generated by Django 5.2.8 on 2026-02-06 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0017_unidad_hereda_liderazgo'),
        ('formacion_app', '0007_rolformativo_sesiongrupo_uniq_sesion_grupo_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programaeducativo',
            name='unidad_responsable',
            field=models.ForeignKey(blank=True, help_text='Unidad responsable del programa (ministerio/departamento).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_responsables', to='estructura_app.unidad'),
        ),
    ]
