# Generated by Django 5.2.8 on 2025-12-17 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miembros_app', '0012_miembro_codigo_miembro'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('es_liderazgo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('orden', models.PositiveIntegerField(default=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de unidad',
                'verbose_name_plural': 'Tipos de unidad',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijas', to='estructura_app.unidad')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='estructura_app.tipounidad')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['tipo__orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('miembo_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos_unidad', to='miembros_app.miembro')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='estructura_app.rolunidad')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='estructura_app.unidad')),
            ],
            options={
                'verbose_name': 'Cargo en unidad',
                'verbose_name_plural': 'Cargos en unidad',
                'ordering': ['-vigente', 'unidad__nombre', 'rol__orden'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('miembro', 'Miembro'), ('colaborador', 'Colaborador'), ('invitado', 'Invitado')], default='miembro', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('miembo_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias_unidad', to='miembros_app.miembro')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='estructura_app.unidad')),
            ],
            options={
                'verbose_name': 'Membresía de unidad',
                'verbose_name_plural': 'Membresías de unidad',
                'ordering': ['-activo', 'unidad__nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='unidad',
            constraint=models.UniqueConstraint(fields=('tipo', 'nombre', 'padre'), name='uniq_unidad_por_tipo_nombre_padre'),
        ),
        migrations.AddIndex(
            model_name='unidadcargo',
            index=models.Index(fields=['unidad', 'vigente'], name='estructura__unidad__5eb47e_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadcargo',
            index=models.Index(fields=['miembo_fk', 'vigente'], name='estructura__miembo__e8d1dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='unidadmembresia',
            constraint=models.UniqueConstraint(fields=('miembo_fk', 'unidad'), name='uniq_miembro_unidad'),
        ),
    ]
