# Generated by Django 5.2.8 on 2025-12-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Unidad', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AddField(
            model_name='unidad',
            name='categoria',
            field=models.CharField(choices=[('liderazgo', 'Liderazgo'), ('evangelismo', 'Evangelismo'), ('servicio', 'Servicio'), ('adoracion', 'Adoración'), ('conexion', 'Conexión')], default='servicio', max_length=20),
        ),
        migrations.AddField(
            model_name='unidad',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='unidad',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='motivo_cierre',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='unidad',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='orden',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='unidad',
            name='tipo_estructura',
            field=models.CharField(choices=[('grupo', 'Grupo'), ('departamento', 'Departamento'), ('ministerio', 'Ministerio'), ('celula', 'Célula'), ('equipo', 'Equipo'), ('comision', 'Comisión'), ('otro', 'Otro')], default='ministerio', max_length=20),
        ),
        migrations.AddField(
            model_name='unidad',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='unidad',
            index=models.Index(fields=['activa', 'visible'], name='estructura__activa_806dea_idx'),
        ),
        migrations.AddIndex(
            model_name='unidad',
            index=models.Index(fields=['tipo_estructura', 'categoria'], name='estructura__tipo_es_14652f_idx'),
        ),
        migrations.AddIndex(
            model_name='unidad',
            index=models.Index(fields=['padre'], name='estructura__padre_i_df12c5_idx'),
        ),
    ]
