# Generated by Django 5.2.8 on 2025-12-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0002_alter_unidad_options_unidad_categoria_unidad_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('orden', models.PositiveIntegerField(default=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de unidad',
                'verbose_name_plural': 'Categorías de unidad',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
