# Generated by Django 5.2.8 on 2025-12-18 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0003_categoriaunidad'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='unidad',
            new_name='estructura__tipo_es_b830be_idx',
            old_name='estructura__tipo_es_14652f_idx',
        ),
        migrations.AlterField(
            model_name='unidad',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='estructura_app.categoriaunidad'),
        ),
    ]
