# Generated by Django 5.2.8 on 2025-12-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0004_rename_estructura__tipo_es_14652f_idx_estructura__tipo_es_b830be_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.RemoveIndex(
            model_name='unidad',
            name='estructura__tipo_es_b830be_idx',
        ),
        migrations.RemoveField(
            model_name='unidad',
            name='tipo_estructura',
        ),
        migrations.AddIndex(
            model_name='unidad',
            index=models.Index(fields=['categoria'], name='estructura__categor_2d4b4b_idx'),
        ),
    ]
