# Generated by Django 5.2.8 on 2025-12-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0005_alter_unidad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipounidad',
            name='icono',
            field=models.CharField(default='account_tree', help_text='Nombre del icono Material Icons (ej: groups, folder)', max_length=40),
        ),
    ]
