# Generated by Django 5.2.8 on 2025-12-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0006_tipounidad_icono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolunidad',
            name='es_liderazgo',
        ),
        migrations.AddField(
            model_name='rolunidad',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rolunidad',
            name='tipo',
            field=models.CharField(choices=[('LIDERAZGO', 'Liderazgo'), ('PARTICIPACION', 'Miembro (participación)'), ('TRABAJO', 'Trabajo (servicio)')], default='PARTICIPACION', max_length=20),
        ),
    ]
