# Generated by Django 5.2.8 on 2025-12-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0007_remove_rolunidad_es_liderazgo_rolunidad_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='reglas',
            field=models.JSONField(blank=True, default=dict, help_text='Reglas de membresía, acceso y restricciones de la unidad'),
        ),
    ]
