# Generated by Django 5.2.8 on 2025-12-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0008_unidad_reglas'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='edad_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='edad_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
