# Generated by Django 5.2.8 on 2025-12-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0009_unidad_edad_max_unidad_edad_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='unidades/'),
        ),
    ]
