# Generated by Django 5.2.8 on 2025-12-20 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0010_unidad_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmembresia',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='estructura_app.rolunidad'),
        ),
    ]
