# Generated by Django 5.2.8 on 2025-12-22 18:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0011_unidadmembresia_rol'),
        ('miembros_app', '0013_miembro_codigo_seguimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('titulo', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('REUNION', 'Reunión'), ('SALIDA', 'Salida'), ('VISITA', 'Visita'), ('EVENTO', 'Evento'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('lugar', models.CharField(blank=True, max_length=120)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, related_name='actividades_participa', to='miembros_app.miembro')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades_responsable', to='miembros_app.miembro')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='estructura_app.unidad')),
            ],
            options={
                'verbose_name': 'Actividad de unidad',
                'verbose_name_plural': 'Actividades de unidad',
                'ordering': ['-fecha', '-creado_en'],
                'indexes': [models.Index(fields=['unidad', 'fecha'], name='estructura__unidad__5f3b22_idx'), models.Index(fields=['unidad', 'tipo'], name='estructura__unidad__4d887a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReporteUnidadPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('resumen', models.JSONField(blank=True, default=dict)),
                ('reflexion', models.TextField(blank=True)),
                ('necesidades', models.TextField(blank=True)),
                ('plan_proximo', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_periodo', to='estructura_app.unidad')),
            ],
            options={
                'verbose_name': 'Reporte por período',
                'verbose_name_plural': 'Reportes por período',
                'ordering': ['-anio', '-mes', 'unidad__nombre'],
                'indexes': [models.Index(fields=['unidad', 'anio', 'mes'], name='estructura__unidad__0c264a_idx')],
                'constraints': [models.UniqueConstraint(fields=('unidad', 'anio', 'mes'), name='uniq_reporte_unidad_anio_mes')],
            },
        ),
    ]
