# Generated by Django 5.2.8 on 2025-12-26 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0012_actividadunidad_reporteunidadperiodo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteUnidadCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('trimestre', 'Trimestral'), ('anio', 'Anual')], max_length=12)),
                ('trimestre', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resumen', models.JSONField(blank=True, default=dict)),
                ('reflexion', models.TextField(blank=True, default='')),
                ('necesidades', models.TextField(blank=True, default='')),
                ('plan_proximo', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_cierre', to='estructura_app.unidad')),
            ],
            options={
                'ordering': ['-anio', '-tipo', '-trimestre'],
                'constraints': [models.UniqueConstraint(fields=('unidad', 'anio', 'tipo', 'trimestre'), name='uniq_reporte_unidad_cierre')],
            },
        ),
    ]
