# Generated by Django 5.2.8 on 2026-01-10 13:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0013_reporteunidadcierre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], default='INGRESO', max_length=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('concepto', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('anulado', models.BooleanField(default=False)),
                ('motivo_anulacion', models.CharField(blank=True, default='', max_length=180)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_unidad_creados', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='estructura_app.unidad')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['unidad', 'fecha'], name='estructura__unidad__fa8fa4_idx'), models.Index(fields=['unidad', 'tipo'], name='estructura__unidad__e8b46c_idx'), models.Index(fields=['unidad', 'anulado'], name='estructura__unidad__aeb66b_idx')],
            },
        ),
    ]
