# Generated by Django 5.2.8 on 2026-01-10 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0014_movimientounidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientounidad',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_unidad_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MovimientoUnidadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ANULAR', 'Anular')], max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fecha_antes', models.DateField(blank=True, null=True)),
                ('fecha_despues', models.DateField(blank=True, null=True)),
                ('concepto_antes', models.CharField(blank=True, default='', max_length=255)),
                ('concepto_despues', models.CharField(blank=True, default='', max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='estructura_app.movimientounidad')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_unidad_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
