# Generated by Django 5.2.8 on 2026-01-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0015_movimientounidad_actualizado_por_movimientounidadlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['orden', 'nombre'], 'permissions': [('ver_dashboard_estructura', 'Puede ver el dashboard de Estructura')]},
        ),
    ]
