# Generated by Django 5.2.8 on 2026-01-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0016_alter_unidad_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='hereda_liderazgo',
            field=models.BooleanField(default=True, help_text='Indica si la unidad hereda líderes de la unidad padre.'),
        ),
    ]
