# Generated by Django 5.2.8 on 2026-03-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0017_unidad_hereda_liderazgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='modo_asignacion',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], default='manual', help_text='Define si la unidad se gestiona manualmente o por reglas automáticas.', max_length=20),
        ),
    ]
