# Generated by Django 5.2.8 on 2026-03-14 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0018_unidad_modo_asignacion'),
        ('miembros_app', '0040_miembrorelacion_unique_relacion_por_tenant'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reporteunidadcierre',
            name='uniq_reporte_unidad_cierre',
        ),
        migrations.RemoveConstraint(
            model_name='reporteunidadperiodo',
            name='uniq_reporte_unidad_anio_mes',
        ),
        migrations.RemoveConstraint(
            model_name='unidad',
            name='uniq_unidad_por_tipo_nombre_padre',
        ),
        migrations.RemoveConstraint(
            model_name='unidadmembresia',
            name='uniq_miembro_unidad',
        ),
        migrations.AddField(
            model_name='actividadunidad',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_unidad', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriaunidad',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorias_unidad', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientounidad',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_unidad', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientounidadlog',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logs_movimientos_unidad', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporteunidadcierre',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_cierre', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporteunidadperiodo',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_periodo', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolunidad',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='roles_unidad', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipounidad',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_unidad', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidad',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadcargo',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cargos_unidad', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadmembresia',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='membresias_unidad', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriaunidad',
            name='codigo',
            field=models.SlugField(max_length=30),
        ),
        migrations.AlterField(
            model_name='categoriaunidad',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='rolunidad',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tipounidad',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AddIndex(
            model_name='actividadunidad',
            index=models.Index(fields=['tenant'], name='estructura__tenant__99ea1d_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriaunidad',
            index=models.Index(fields=['tenant'], name='estructura__tenant__2c6333_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientounidad',
            index=models.Index(fields=['tenant'], name='estructura__tenant__5fb1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientounidadlog',
            index=models.Index(fields=['tenant'], name='estructura__tenant__8f1e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='reporteunidadperiodo',
            index=models.Index(fields=['tenant'], name='estructura__tenant__f37984_idx'),
        ),
        migrations.AddIndex(
            model_name='rolunidad',
            index=models.Index(fields=['tenant'], name='estructura__tenant__c646c7_idx'),
        ),
        migrations.AddIndex(
            model_name='tipounidad',
            index=models.Index(fields=['tenant'], name='estructura__tenant__294a36_idx'),
        ),
        migrations.AddIndex(
            model_name='unidad',
            index=models.Index(fields=['tenant'], name='estructura__tenant__2f6ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadcargo',
            index=models.Index(fields=['tenant'], name='estructura__tenant__3399fe_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadmembresia',
            index=models.Index(fields=['tenant'], name='estructura__tenant__b70817_idx'),
        ),
        migrations.AddConstraint(
            model_name='categoriaunidad',
            constraint=models.UniqueConstraint(fields=('tenant', 'codigo'), name='uniq_categoria_unidad_codigo'),
        ),
        migrations.AddConstraint(
            model_name='categoriaunidad',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='uniq_categoria_unidad_nombre'),
        ),
        migrations.AddConstraint(
            model_name='reporteunidadcierre',
            constraint=models.UniqueConstraint(fields=('tenant', 'unidad', 'anio', 'tipo', 'trimestre'), name='uniq_reporte_unidad_cierre'),
        ),
        migrations.AddConstraint(
            model_name='reporteunidadperiodo',
            constraint=models.UniqueConstraint(fields=('tenant', 'unidad', 'anio', 'mes'), name='uniq_reporte_unidad_anio_mes'),
        ),
        migrations.AddConstraint(
            model_name='rolunidad',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='uniq_rol_unidad_nombre'),
        ),
        migrations.AddConstraint(
            model_name='tipounidad',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='uniq_tipo_unidad_nombre'),
        ),
        migrations.AddConstraint(
            model_name='unidad',
            constraint=models.UniqueConstraint(fields=('tenant', 'tipo', 'nombre', 'padre'), name='uniq_unidad_por_tipo_nombre_padre'),
        ),
        migrations.AddConstraint(
            model_name='unidadmembresia',
            constraint=models.UniqueConstraint(fields=('tenant', 'miembo_fk', 'unidad'), name='uniq_miembro_unidad'),
        ),
    ]
