# Generated by Django 5.2.8 on 2025-11-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre visible')),
                ('code', models.SlugField(help_text='Ej: miembros, finanzas, discipulado', unique=True, verbose_name='Código interno')),
                ('description', models.TextField(blank=True, verbose_name='Descripción corta')),
                ('icon', models.CharField(blank=True, help_text='Ej: fa-users, fa-church, etc.', max_length=100, verbose_name='Icono (opcional)')),
                ('color', models.CharField(default='#0097A7', help_text='Ej: #0097A7', max_length=20, verbose_name='Color de tarjeta')),
                ('url_name', models.CharField(help_text='El name de la ruta en urls.py', max_length=100, verbose_name='Nombre de URL')),
                ('is_enabled', models.BooleanField(default=True, help_text='Si está desmarcado, no aparece en la pantalla de inicio.', verbose_name='Módulo activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Posición del módulo en el home.', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['order', 'name'],
            },
        ),
    ]
