# Generated by Django 5.2.8 on 2025-11-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_iglesia', models.CharField(default='Iglesia Torre Fuerte', max_length=150, verbose_name='Nombre de la iglesia')),
                ('email_oficial', models.EmailField(blank=True, max_length=254, verbose_name='Correo oficial')),
                ('telefono_oficial', models.CharField(blank=True, max_length=50, verbose_name='Teléfono oficial')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracion/', verbose_name='Logo principal')),
                ('edad_minima_miembro_oficial', models.PositiveIntegerField(default=12, help_text='Años para considerar a alguien miembro oficial / bautizable.', verbose_name='Edad mínima miembro oficial')),
                ('whatsapp_oficial', models.CharField(blank=True, help_text='Solo números con código de país, sin espacios ni guiones.', max_length=50, verbose_name='WhatsApp oficial')),
                ('pie_cartas', models.TextField(blank=True, help_text='Se puede usar al final de las cartas automáticas.', verbose_name='Texto de pie de cartas')),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuración del sistema',
            },
        ),
    ]
