# Generated by Django 5.2.8 on 2025-11-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracionsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='color_primario',
            field=models.CharField(default='#0097A7', help_text='Color principal de la interfaz (hex).', max_length=20, verbose_name='Color primario del sistema'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='color_secundario',
            field=models.CharField(default='#F59E0B', help_text='Color de acento (hex).', max_length=20, verbose_name='Color secundario del sistema'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='denominacion',
            field=models.CharField(blank=True, help_text='Ej: Pentecostal, Bautista, Independiente, etc.', max_length=100, verbose_name='Denominación'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='formato_fecha_corta',
            field=models.CharField(default='DD/MM/YYYY', help_text='Ej: DD/MM/YYYY', max_length=20, verbose_name='Formato fecha corta'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='formato_fecha_larga',
            field=models.CharField(default='D de MMMM de YYYY', help_text='Ej: 25 de noviembre de 2025', max_length=50, verbose_name='Formato fecha larga'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='lema',
            field=models.CharField(blank=True, help_text="Ej: 'Firmes en la Roca', 'Un refugio en la tormenta', etc.", max_length=150, verbose_name='Lema / frase institucional'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='logo_oscuro',
            field=models.ImageField(blank=True, null=True, upload_to='configuracion/', verbose_name='Logo para fondo oscuro'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='modo_impresion',
            field=models.CharField(choices=[('formal', 'Formal'), ('minimalista', 'Minimalista'), ('clasico', 'Clásico')], default='formal', help_text='Afecta el estilo de cartas, certificados y reportes.', max_length=20, verbose_name='Modo de impresión'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='nombre_corto',
            field=models.CharField(blank=True, help_text='Ej: Torre Fuerte, TF, etc.', max_length=100, verbose_name='Nombre corto'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='plantilla_pdf_fondo',
            field=models.ImageField(blank=True, help_text='Imagen suave para utilizar como fondo o marca de agua en documentos.', null=True, upload_to='configuracion/', verbose_name='Fondo para PDFs / cartas'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='zona_horaria',
            field=models.CharField(default='America/Santo_Domingo', help_text='Ej: America/Santo_Domingo', max_length=50, verbose_name='Zona horaria'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='configuracion/', verbose_name='Logo principal (fondo claro)'),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='pie_cartas',
            field=models.TextField(blank=True, help_text='Se puede mostrar al final de las cartas de salida, traslados, etc.', verbose_name='Texto de pie de cartas'),
        ),
        migrations.AlterField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, help_text='Ej: groups, dashboard, settings (Material Icons)', max_length=100, verbose_name='Icono (opcional)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='url_name',
            field=models.CharField(help_text='El name de la ruta en urls.py, ej: core:configuracion', max_length=100, verbose_name='Nombre de URL'),
        ),
    ]
