# Generated by Django 5.2.8 on 2025-11-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracionsistema_color_primario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='email_from_address',
            field=models.EmailField(blank=True, help_text='Dirección desde la que el sistema enviará correos.', max_length=254, verbose_name='Correo remitente de correos'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='email_from_name',
            field=models.CharField(blank=True, help_text='Ej: Iglesia Torre Fuerte.', max_length=100, verbose_name='Nombre remitente de correos'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='email_pastor',
            field=models.EmailField(blank=True, help_text='Correo para recibir notificaciones o copias de reportes.', max_length=254, verbose_name='Correo del pastor / administración'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='enviar_copia_a_pastor',
            field=models.BooleanField(default=False, help_text='Si está marcado, el sistema enviará copia al correo del pastor en los correos oficiales.', verbose_name='Enviar copia al pastor'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mostrar_direccion_en_reportes',
            field=models.BooleanField(default=True, help_text='Si está marcado, la dirección aparecerá bajo el logo en los reportes.', verbose_name='Mostrar dirección en reportes'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mostrar_logo_en_reportes',
            field=models.BooleanField(default=True, help_text='Si está marcado, el logo aparecerá en los reportes impresos.', verbose_name='Mostrar logo en reportes'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='pastor_principal',
            field=models.CharField(blank=True, help_text='Nombre que se mostrará en cartas y documentos oficiales.', max_length=150, verbose_name='Pastor principal'),
        ),
    ]
