# Generated by Django 5.2.8 on 2025-12-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracionsistema_email_from_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='encargado_comunicaciones',
            field=models.CharField(blank=True, help_text='Ej: Secretaría, Administración, Ministerio de Comunicaciones.', max_length=150, verbose_name='Nombre del encargado de comunicaciones'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='horario_atencion',
            field=models.CharField(blank=True, help_text='Ej: Lun–Vie 9:00 a.m. – 6:00 p.m.', max_length=150, verbose_name='Horario de atención'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='mensaje_institucional_corto',
            field=models.CharField(blank=True, help_text='Se puede usar como firma en correos y reportes.', max_length=150, verbose_name='Mensaje institucional corto'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='sitio_web',
            field=models.URLField(blank=True, verbose_name='Página web oficial'),
        ),
    ]
