# Generated by Django 5.2.8 on 2025-12-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configuracionsistema_encargado_comunicaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='codigo_miembro_prefijo',
            field=models.CharField(default='TF-', help_text='Ej: TF-, IB-, CC-, etc.', max_length=20, verbose_name='Prefijo para código de miembro'),
        ),
    ]
