# Generated by Django 5.2.8 on 2026-01-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_documentocompartido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocompartido',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
    ]
