# Generated by Django 5.2.8 on 2026-01-30 03:03

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_documentocompartido_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocompartido',
            name='archivo',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='docs_compartidos/'),
        ),
    ]
