# Generated by Django 5.2.8 on 2026-02-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_documentocompartido_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='codigo_iglesia',
            field=models.CharField(blank=True, default='', help_text='Código oficial de la iglesia en el concilio (si aplica).', max_length=50),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='conyuge_pastor',
            field=models.CharField(blank=True, default='', help_text='Nombre del cónyuge del pastor.', max_length=150),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='credencial_conyuge',
            field=models.CharField(blank=True, default='', help_text='Credencial del cónyuge (solo números/letras).', max_length=30),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='credencial_pastor',
            field=models.CharField(blank=True, default='', help_text='Credencial ministerial del pastor (solo números/letras).', max_length=30),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='presbiterio_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre del presbiterio al que pertenece la iglesia.', max_length=150),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='presbitero_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre del presbítero supervisor.', max_length=150),
        ),
    ]
