# Generated by Django 5.2.8 on 2026-02-18 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_configuracionsistema_codigo_iglesia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de expiración')),
                ('motivo', models.CharField(default='Prueba del sistema', help_text='Ej: Prueba sistema, Demo cliente, Evaluación, etc.', max_length=200, verbose_name='Motivo')),
                ('notas', models.TextField(blank=True, help_text='Información adicional sobre este usuario de prueba.', verbose_name='Notas adicionales')),
                ('activo', models.BooleanField(default=True, help_text='Se desactiva automáticamente al expirar.', verbose_name='Activo')),
                ('password_temporal', models.CharField(blank=True, help_text='Se muestra solo al crear. Guardar para compartir.', max_length=50, verbose_name='Contraseña generada')),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('accesos_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de accesos')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_temp_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_temporal', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario Temporal',
                'verbose_name_plural': 'Usuarios Temporales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
