# Generated by Django 5.2.8 on 2026-03-05 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_usuariotemporal'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsistema',
            options={'verbose_name': 'Configuración del sistema', 'verbose_name_plural': 'Configuraciones del sistema'},
        ),
        migrations.AlterModelOptions(
            name='documentocompartido',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Documento compartido', 'verbose_name_plural': 'Documentos compartidos'},
        ),
        migrations.AlterModelOptions(
            name='userengagement',
            options={'verbose_name': 'Engagement de Usuario', 'verbose_name_plural': 'Engagement de Usuarios'},
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentocompartido',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userengagement',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userloginhistory',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariotemporal',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='nombre_iglesia',
            field=models.CharField(default='Mi Iglesia', max_length=150, verbose_name='Nombre de la iglesia'),
        ),
        migrations.AlterField(
            model_name='userengagement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='configuracionsistema',
            constraint=models.UniqueConstraint(fields=('tenant',), name='unique_configuracion_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='userengagement',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='unique_engagement_por_tenant_user'),
        ),
    ]
