# Generated by Django 5.2.8 on 2026-03-17 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_configuracionsistema_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsistema',
            options={'permissions': [('acceso_sistema', 'Puede acceder al sistema administrativo')], 'verbose_name': 'Configuración del sistema', 'verbose_name_plural': 'Configuraciones del sistema'},
        ),
    ]
