# Generated by Django 5.2.8 on 2026-01-24 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('CULTO', 'Culto'), ('REUNION', 'Reunión'), ('EVENTO', 'Evento'), ('ENSAYO', 'Ensayo'), ('CAMPANA', 'Campaña'), ('SOCIAL', 'Actividad social'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('lugar', models.CharField(blank=True, default='', max_length=120)),
                ('responsable_texto', models.CharField(blank=True, default='', max_length=120)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['fecha', 'hora_inicio', 'titulo'],
            },
        ),
    ]
