# Generated by Django 5.2.8 on 2026-01-25 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_app', '0001_initial'),
        ('estructura_app', '0017_unidad_hereda_liderazgo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_agenda', to='estructura_app.unidad', verbose_name='Unidad / Ministerio'),
        ),
    ]
