# Generated by Django 5.2.8 on 2026-01-30 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_app', '0002_actividad_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadRecordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_antes', models.PositiveIntegerField(default=60)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='agenda_app.actividad')),
            ],
            options={
                'indexes': [models.Index(fields=['minutos_antes', 'enviado_en'], name='agenda_app__minutos_43388b_idx')],
                'unique_together': {('actividad', 'minutos_antes')},
            },
        ),
    ]
