# Generated by Django 5.2.8 on 2026-02-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_app', '0003_actividadrecordatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='visibilidad',
            field=models.CharField(choices=[('PUBLICO', 'Público'), ('PRIVADO', 'Privado')], db_index=True, default='PRIVADO', max_length=10),
        ),
    ]
