# Generated by Django 5.2.8 on 2026-04-07 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_app', '0004_actividad_visibilidad'),
        ('estructura_app', '0019_remove_reporteunidadcierre_uniq_reporte_unidad_cierre_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='tenants.tenant', verbose_name='Tenant'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='actividad',
            index=models.Index(fields=['tenant', 'fecha', 'estado'], name='agenda_app__tenant__158520_idx'),
        ),
    ]
