# Generated by Django 5.2.8 on 2026-03-06 13:29

import django.db.models.deletion
import documentos_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('icono', models.CharField(blank=True, default='label', max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de documento',
                'verbose_name_plural': 'Categorías de documentos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EtiquetaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('color', models.CharField(blank=True, default='#6b7280', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, default='', help_text='Color opcional en HEX. Ej: #2563eb', max_length=20)),
                ('icono', models.CharField(blank=True, default='folder', help_text='Nombre del icono Material Icons', max_length=50)),
                ('visibilidad', models.CharField(choices=[('privado', 'Privado'), ('interno', 'Interno'), ('lideres', 'Solo líderes'), ('administracion', 'Administración')], default='interno', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carpeta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcarpetas', to='documentos_app.carpeta')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gestion_propios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('carpeta_padre', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=documentos_app.models.documento_upload_path)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('archivado', 'Archivado'), ('vencido', 'Vencido')], default='borrador', max_length=20)),
                ('visibilidad', models.CharField(choices=[('privado', 'Privado'), ('interno', 'Interno'), ('lideres', 'Solo líderes'), ('administracion', 'Administración')], default='interno', max_length=20)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('es_oficial', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carpeta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='documentos_app.carpeta')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='documentos_app.categoriadocumento')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gestion_creados', to=settings.AUTH_USER_MODEL)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_propios', to=settings.AUTH_USER_MODEL)),
                ('etiquetas', models.ManyToManyField(blank=True, related_name='documentos', to='documentos_app.etiquetadocumento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at', 'titulo'],
            },
        ),
    ]
