# Generated by Django 5.2.8 on 2026-03-06 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos_app', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carpeta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriadocumento',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etiquetadocumento',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gestion_carpetas_propias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoriadocumento',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='categoriadocumento',
            name='slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='documento',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_gestion_propios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='etiquetadocumento',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='etiquetadocumento',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='carpeta',
            unique_together={('tenant', 'carpeta_padre', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='categoriadocumento',
            unique_together={('tenant', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='etiquetadocumento',
            unique_together={('tenant', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='categoriadocumento',
            index=models.Index(fields=['tenant', 'nombre'], name='documentos__tenant__507803_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriadocumento',
            index=models.Index(fields=['tenant', 'slug'], name='documentos__tenant__f3f7b5_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tenant', 'titulo'], name='documentos__tenant__a69b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tenant', 'estado'], name='documentos__tenant__5cd7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tenant', 'eliminado'], name='documentos__tenant__f0e4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['tenant', 'created_at'], name='documentos__tenant__1352f6_idx'),
        ),
        migrations.AddIndex(
            model_name='etiquetadocumento',
            index=models.Index(fields=['tenant', 'nombre'], name='documentos__tenant__d90739_idx'),
        ),
        migrations.AddIndex(
            model_name='etiquetadocumento',
            index=models.Index(fields=['tenant', 'slug'], name='documentos__tenant__3109b5_idx'),
        ),
    ]
