# Generated by Django 5.2.8 on 2026-03-17 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones_app', '0002_pushsubscription'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushsubscription',
            options={'verbose_name': 'Suscripción Push', 'verbose_name_plural': 'Suscripciones Push'},
        ),
        migrations.RemoveIndex(
            model_name='pushsubscription',
            name='notificacio_user_id_0a0895_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tenants.tenant', verbose_name='Tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='tenants.tenant', verbose_name='Tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['tenant', 'usuario', 'leida'], name='notificacio_tenant__66118b_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['tenant', 'user', 'activo'], name='notificacio_tenant__23642c_idx'),
        ),
        migrations.AddConstraint(
            model_name='pushsubscription',
            constraint=models.UniqueConstraint(fields=('tenant', 'endpoint'), name='unique_endpoint_per_tenant'),
        ),
    ]
