# Generated by Django 5.2.8 on 2026-02-01 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo_qr', '0001_initial'),
        ('miembros_app', '0036_miembrorelacion_es_inferida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrtoken',
            name='miembro_id',
        ),
        migrations.AddField(
            model_name='qrtoken',
            name='miembro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_token', to='miembros_app.miembro'),
        ),
    ]
