# Generated by Django 5.2.8 on 2026-02-01 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codigo_qr', '0002_remove_qrtoken_miembro_id_qrtoken_miembro'),
        ('miembros_app', '0036_miembrorelacion_es_inferida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QrEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('sin_telefono', 'Sin teléfono')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_envios_creados', to=settings.AUTH_USER_MODEL)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_envios_enviados', to=settings.AUTH_USER_MODEL)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_envios', to='miembros_app.miembro')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='codigo_qr.qrtoken')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['estado'], name='codigo_qr_q_estado_ab8836_idx'), models.Index(fields=['creado_en'], name='codigo_qr_q_creado__9be580_idx')],
            },
        ),
    ]
