# Generated by Django 5.2.8 on 2026-01-05 15:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miembros_app', '0015_miembro_situacion_economica_miembro_tiene_vehiculo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoActualizacionDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ultimo_envio_en', models.DateTimeField(blank=True, null=True)),
                ('miembro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceso_actualizacion_datos', to='miembros_app.miembro')),
            ],
            options={
                'verbose_name': 'Acceso: actualización de datos',
                'verbose_name_plural': 'Accesos: actualización de datos',
            },
        ),
        migrations.CreateModel(
            name='SolicitudActualizacionMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aplicada', 'Aplicada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=20)),
                ('empleador', models.CharField(blank=True, max_length=150)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('telefono_trabajo', models.CharField(blank=True, max_length=20)),
                ('direccion_trabajo', models.TextField(blank=True)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=150)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20)),
                ('contacto_emergencia_relacion', models.CharField(blank=True, max_length=50)),
                ('tipo_sangre', models.CharField(blank=True, max_length=10)),
                ('alergias', models.TextField(blank=True)),
                ('condiciones_medicas', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('nota_admin', models.TextField(blank=True)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_actualizacion', to='miembros_app.miembro')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_actualizacion_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud: actualización de datos',
                'verbose_name_plural': 'Solicitudes: actualización de datos',
                'ordering': ['-creado_en'],
            },
        ),
    ]
