# Generated by Django 5.2.8 on 2026-01-05 16:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAltaMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('estado_miembro', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('observacion', 'En observación'), ('disciplina', 'En disciplina'), ('descarriado', 'Descarriado'), ('catecumeno', 'Catecúmeno')], max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('nota_admin', models.TextField(blank=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_alta_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud: alta (registro masivo)',
                'verbose_name_plural': 'Solicitudes: altas (registro masivo)',
                'ordering': ['-creado_en'],
            },
        ),
    ]
