# Generated by Django 5.2.8 on 2026-01-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0002_solicitudaltamiembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudaltamiembro',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitudaltamiembro',
            name='sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solicitudaltamiembro',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
