# Generated by Django 5.2.8 on 2026-01-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0003_solicitudaltamiembro_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltaMasivaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Alta Masiva',
                'verbose_name_plural': 'Configuración Alta Masiva',
            },
        ),
    ]
