# Generated by Django 5.2.8 on 2026-01-07 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0004_altamasivaconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altamasivaconfig',
            options={},
        ),
    ]
