# Generated by Django 5.2.8 on 2026-01-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0005_alter_altamasivaconfig_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudaltamiembro',
            name='cedula',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudaltamiembro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='solicitudes_alta/fotos/'),
        ),
    ]
