# Generated by Django 5.2.8 on 2026-01-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0006_solicitudaltamiembro_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudactualizacionmiembro',
            name='fecha_bautismo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudactualizacionmiembro',
            name='fecha_conversion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudactualizacionmiembro',
            name='fecha_ingreso_iglesia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudactualizacionmiembro',
            name='iglesia_anterior',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
