# Generated by Django 5.2.8 on 2026-01-08 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0007_solicitudactualizacionmiembro_fecha_bautismo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionDatosConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('campos_permitidos', models.JSONField(blank=True, default=list)),
                ('actualizado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Configuración de Actualización de Datos',
                'verbose_name_plural': 'Configuración de Actualización de Datos',
            },
        ),
    ]
