# Generated by Django 5.2.8 on 2026-01-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0008_actualizaciondatosconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudactualizacionmiembro',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudactualizacionmiembro',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='solicitudactualizacionmiembro',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solicitudactualizacionmiembro',
            name='nivel_educativo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='solicitudactualizacionmiembro',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='solicitudactualizacionmiembro',
            name='profesion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solicitudactualizacionmiembro',
            name='telefono_secundario',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
