# Generated by Django 5.2.8 on 2026-01-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0009_solicitudactualizacionmiembro_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudaltamiembro',
            name='estado_miembro',
            field=models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('observacion', 'En observación'), ('disciplina', 'En disciplina'), ('descarriado', 'Descarriado'), ('catecumeno', 'Catecúmeno'), ('trasladado', 'Trasladado')], max_length=30),
        ),
    ]
