# Generated by Django 5.2.8 on 2026-01-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0010_alter_solicitudaltamiembro_estado_miembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='altamasivaconfig',
            name='mensaje_compartir',
            field=models.TextField(default='Registro de miembro\n\nHola 👋\nEstamos probando un formulario digital para registrar datos de la iglesia.\n¿Podrías llenarlo y decirme si algo no se entiende?\n\nGracias 🙏'),
        ),
    ]
