# Generated by Django 5.2.8 on 2026-02-13 19:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0011_altamasivaconfig_mensaje_compartir'),
        ('miembros_app', '0036_miembrorelacion_es_inferida'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoAltaFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ultimo_envio_en', models.DateTimeField(blank=True, null=True)),
                ('jefe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceso_alta_familia', to='miembros_app.miembro')),
            ],
        ),
        migrations.CreateModel(
            name='AltaFamiliaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('conyuge_id', models.IntegerField(blank=True, null=True)),
                ('padre_id', models.IntegerField(blank=True, null=True)),
                ('madre_id', models.IntegerField(blank=True, null=True)),
                ('hijos_ids', models.JSONField(blank=True, default=list)),
                ('relaciones_creadas', models.JSONField(blank=True, default=list)),
                ('alertas', models.JSONField(blank=True, default=list)),
                ('jefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='altas_familia_log', to='miembros_app.miembro')),
            ],
        ),
    ]
