# Generated by Django 5.2.8 on 2026-02-13 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0012_accesoaltafamilia_altafamilialog'),
        ('miembros_app', '0036_miembrorelacion_es_inferida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesoaltafamilia',
            name='jefe',
        ),
        migrations.RemoveField(
            model_name='altafamilialog',
            name='jefe',
        ),
        migrations.AddField(
            model_name='altafamilialog',
            name='acceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='actualizacion_datos_miembros.accesoaltafamilia'),
        ),
        migrations.AddField(
            model_name='altafamilialog',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='altas_familia_como_principal', to='miembros_app.miembro'),
        ),
    ]
