# Generated by Django 5.2.8 on 2026-02-13 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0013_remove_accesoaltafamilia_jefe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altafamilialog',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Solicitud: alta de familia', 'verbose_name_plural': 'Solicitudes: alta de familia'},
        ),
        migrations.AddField(
            model_name='altafamilialog',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aplicada', 'Aplicada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='altafamilialog',
            name='ip_origen',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='altafamilialog',
            name='nota_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='altafamilialog',
            name='revisado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='altafamilialog',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_familia_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='altafamilialog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
