# Generated by Django 5.2.8 on 2026-02-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0014_alter_altafamilialog_options_altafamilialog_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudaltamiembro',
            name='estado_miembro',
            field=models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('observacion', 'En observación'), ('disciplina', 'En disciplina'), ('descarriado', 'Descarriado'), ('catecumeno', 'Catecúmeno'), ('trasladado', 'Trasladado'), ('fallecido', 'Fallecido')], max_length=30),
        ),
    ]
