# Generated by Django 5.2.8 on 2026-03-04 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0015_alter_solicitudaltamiembro_estado_miembro'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesoaltafamilia',
            options={'verbose_name': 'Acceso: alta de familia', 'verbose_name_plural': 'Accesos: alta de familia'},
        ),
        migrations.AlterModelOptions(
            name='actualizaciondatosconfig',
            options={'verbose_name': 'Configuración: actualización de datos', 'verbose_name_plural': 'Configuración: actualización de datos'},
        ),
        migrations.AlterModelOptions(
            name='altamasivaconfig',
            options={'verbose_name': 'Configuración: alta masiva', 'verbose_name_plural': 'Configuración: alta masiva'},
        ),
        migrations.AddField(
            model_name='accesoactualizaciondatos',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accesos_actualizacion_datos', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accesoaltafamilia',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accesos_alta_familia', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actualizaciondatosconfig',
            name='tenant',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actualizacion_datos_config', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='altafamilialog',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='altas_familia_logs', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='altamasivaconfig',
            name='tenant',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alta_masiva_config', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudactualizacionmiembro',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_actualizacion_miembro', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudaltamiembro',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_alta_miembro', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actualizaciondatosconfig',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
