# Generated by Django 5.2.8 on 2026-03-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0016_alter_accesoaltafamilia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudaltamiembro',
            name='ciudad',
            field=models.CharField(choices=[('Higuey', 'Higüey'), ('Punta Cana', 'Punta Cana'), ('San Rafael del Yuma', 'San Rafael del Yuma')], default='Higuey', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudaltamiembro',
            name='sector',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudaltamiembro',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
