# Generated by Django 5.2.8 on 2026-03-04 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0017_solicitudaltamiembro_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudaltamiembro',
            name='fecha_ingreso_iglesia',
            field=models.DateField(default=datetime.date(2026, 3, 4)),
            preserve_default=False,
        ),
    ]
