# Generated by Django 5.2.8 on 2026-03-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualizacion_datos_miembros', '0018_solicitudaltamiembro_fecha_ingreso_iglesia'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudaltamiembro',
            name='apodo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
