# Generated by Django 5.2.8 on 2025-11-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='miembros/fotos/')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=150)),
                ('nacionalidad', models.CharField(blank=True, max_length=100)),
                ('estado_civil', models.CharField(blank=True, max_length=50)),
                ('nivel_educativo', models.CharField(blank=True, max_length=100)),
                ('profesion', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('telefono_secundario', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=20)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=150)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20)),
                ('contacto_emergencia_relacion', models.CharField(blank=True, max_length=100)),
                ('tipo_sangre', models.CharField(blank=True, max_length=10)),
                ('alergias', models.TextField(blank=True)),
                ('condiciones_medicas', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('empleador', models.CharField(blank=True, max_length=150)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('telefono_trabajo', models.CharField(blank=True, max_length=20)),
                ('direccion_trabajo', models.CharField(blank=True, max_length=255)),
                ('estado_miembro', models.CharField(blank=True, max_length=50)),
                ('fecha_ingreso_iglesia', models.DateField(blank=True, null=True)),
                ('iglesia_anterior', models.CharField(blank=True, max_length=150)),
                ('fecha_conversion', models.DateField(blank=True, null=True)),
                ('fecha_bautismo', models.DateField(blank=True, null=True)),
                ('bautizado_confirmado', models.BooleanField(default=False)),
                ('categoria_miembro', models.CharField(blank=True, max_length=100)),
                ('mentor', models.CharField(blank=True, max_length=150)),
                ('lider_celula', models.CharField(blank=True, max_length=150)),
                ('intereses', models.TextField(blank=True, help_text='Áreas de interés (podemos guardar JSON o texto separado por comas).')),
                ('habilidades', models.TextField(blank=True, help_text='Habilidades / talentos (también podemos usar JSON o texto).')),
                ('otros_intereses', models.CharField(blank=True, max_length=255)),
                ('otras_habilidades', models.CharField(blank=True, max_length=255)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'ordering': ['nombres', 'apellidos'],
            },
        ),
    ]
