# Generated by Django 5.1.7 on 2025-11-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembro',
            name='activo',
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado_miembro',
            field=models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('descarriado', 'Descarriado'), ('observacion', 'En observación')], default='activo', max_length=20, verbose_name='Estado del miembro'),
        ),
    ]
