# Generated by Django 5.1.7 on 2025-11-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0002_remove_miembro_activo_alter_miembro_estado_miembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='categoria_edad',
            field=models.CharField(blank=True, choices=[('infante', 'Infante'), ('nino', 'Niño'), ('adolescente', 'Adolescente'), ('joven', 'Jóven'), ('joven_adulto', 'Jóven adulto'), ('caballero', 'Caballero'), ('anciano', 'Anciano')], max_length=20, verbose_name='Categoría de edad'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado_miembro',
            field=models.CharField(blank=True, choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('descarriado', 'Descarriado'), ('observacion', 'En observación')], default='activo', max_length=20, verbose_name='Estado del miembro'),
        ),
    ]
