# Generated by Django 5.1.7 on 2025-11-22 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0003_miembro_categoria_edad_alter_miembro_estado_miembro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='bautizado_confirmado',
            field=models.BooleanField(default=False, help_text='Marcar si se ha confirmado el bautismo del miembro.'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='categoria_miembro',
            field=models.CharField(blank=True, help_text='Categoría pastoral del miembro (Miembro, Líder, Servidor, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='contacto_emergencia_relacion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='direccion_trabajo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado_miembro',
            field=models.CharField(blank=True, choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('descarriado', 'Descarriado'), ('observacion', 'En observación')], help_text='Estado pastoral del miembro (activo, pasivo, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='fecha_bautismo',
            field=models.DateField(blank=True, help_text='Fecha de bautismo en agua.', null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='fecha_conversion',
            field=models.DateField(blank=True, help_text='Fecha aproximada de conversión, si se conoce.', null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='fecha_ingreso_iglesia',
            field=models.DateField(blank=True, help_text='Fecha en que empezó a congregarse en la iglesia.', null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Se usará para calcular la edad y clasificar la categoría.', null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='miembros_fotos/'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='intereses',
            field=models.TextField(blank=True, help_text='Intereses generales (ministerios, áreas de servicio, etc.)'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='nivel_educativo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='MiembroRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacion', models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('hijo', 'Hijo'), ('hija', 'Hija'), ('conyuge', 'Cónyuge'), ('hermano', 'Hermano'), ('hermana', 'Hermana'), ('abuelo', 'Abuelo'), ('abuela', 'Abuela'), ('tutor', 'Tutor / Encargado'), ('otro', 'Otro familiar')], max_length=20)),
                ('vive_junto', models.BooleanField(default=True, help_text='Marcar si vive en la misma casa que este miembro.')),
                ('es_responsable', models.BooleanField(default=False, help_text='Marcar si es responsable principal (económico / tutor).')),
                ('notas', models.TextField(blank=True, help_text='Notas breves sobre la relación familiar (opcional).')),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_como_familiar', to='miembros_app.miembro')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='miembros_app.miembro')),
            ],
            options={
                'verbose_name': 'Relación familiar',
                'verbose_name_plural': 'Relaciones familiares',
            },
        ),
    ]
