# Generated by Django 5.2.8 on 2025-11-23 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0004_alter_miembro_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miembro',
            options={},
        ),
        migrations.AddField(
            model_name='miembro',
            name='es_trasladado',
            field=models.BooleanField(default=False, help_text='Marcar si el miembro viene trasladado de otra iglesia.'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='categoria_edad',
            field=models.CharField(blank=True, choices=[('infante', 'Infante'), ('nino', 'Niño'), ('adolescente', 'Adolescente'), ('joven', 'Jóven'), ('adulto', 'Adulto'), ('adulto_mayor', 'Adulto mayor')], help_text='Categoría de edad calculada automáticamente.', max_length=20),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado_miembro',
            field=models.CharField(blank=True, choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('observacion', 'En observación'), ('disciplina', 'En disciplina'), ('descarriado', 'Descarriado'), ('catecumeno', 'Catecúmeno')], help_text='Estado pastoral del miembro (activo, pasivo, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='habilidades',
            field=models.TextField(blank=True, help_text='Habilidades / talentos (también podemos usar JSON o texto estructurado).'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='otras_habilidades',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='otros_intereses',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='miembrorelacion',
            name='familiar',
            field=models.ForeignKey(help_text='Miembro que es familiar del principal.', on_delete=django.db.models.deletion.CASCADE, related_name='como_familiar_en', to='miembros_app.miembro'),
        ),
        migrations.AlterField(
            model_name='miembrorelacion',
            name='miembro',
            field=models.ForeignKey(help_text='Miembro principal.', on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='miembros_app.miembro'),
        ),
        migrations.AlterField(
            model_name='miembrorelacion',
            name='tipo_relacion',
            field=models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('hijo', 'Hijo/a'), ('conyuge', 'Cónyuge'), ('hermano', 'Hermano/a'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='miembrorelacion',
            name='vive_junto',
            field=models.BooleanField(default=False, help_text='Marcar si viven en la misma casa.'),
        ),
    ]
