# Generated by Django 5.2.8 on 2025-11-25 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0005_alter_miembro_options_miembro_es_trasladado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazonSalidaMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre corto de la razón de salida (Traslado, Distancia, etc.).', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la razón.')),
                ('activo', models.BooleanField(default=True, help_text='Si se desmarca, deja de aparecer en el selector, pero se mantiene el histórico.')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Permite ordenar las razones en el selector.')),
            ],
            options={
                'verbose_name': 'Razón de salida de miembro',
                'verbose_name_plural': 'Razones de salida de miembros',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='miembro',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está desmarcado, el miembro ya no pertenece a la iglesia Torre Fuerte.'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='comentario_salida',
            field=models.TextField(blank=True, help_text='Comentarios adicionales sobre la salida (opcional).'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='fecha_salida',
            field=models.DateField(blank=True, help_text='Fecha en que dejó de pertenecer a la iglesia Torre Fuerte.', null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='categoria_edad',
            field=models.CharField(blank=True, choices=[('infante', 'Infante'), ('nino', 'Niño'), ('adolescente', 'Adolescente'), ('joven', 'Jóven'), ('adulto', 'Adulto'), ('adulto_mayor', 'Adulto mayor')], help_text='Clasificación automática según la edad.', max_length=20),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='habilidades',
            field=models.TextField(blank=True, help_text='Habilidades específicas (música, docencia, administración, etc.)'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas pastorales o información relevante.'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='otras_habilidades',
            field=models.TextField(blank=True, help_text='Otras habilidades no contempladas arriba.'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='otros_intereses',
            field=models.TextField(blank=True, help_text='Otros intereses no contemplados arriba.'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='razon_salida',
            field=models.ForeignKey(blank=True, help_text='Motivo principal por el que ya no pertenece a la iglesia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembros', to='miembros_app.razonsalidamiembro'),
        ),
    ]
