# Generated by Django 5.2.8 on 2025-11-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0006_razonsalidamiembro_miembro_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=20),
        ),
    ]
