# Generated by Django 5.2.8 on 2025-11-26 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0007_alter_miembro_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='cedula',
            field=models.CharField(blank=True, help_text='Formato: 000-0000000-0', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener el formato 000-0000000-0', regex='^\\d{3}-\\d{7}-\\d$')]),
        ),
        migrations.AddField(
            model_name='miembro',
            name='pasaporte',
            field=models.CharField(blank=True, help_text='Número de pasaporte del miembro.', max_length=20, null=True),
        ),
    ]
