# Generated by Django 5.2.8 on 2025-11-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0008_miembro_cedula_miembro_pasaporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='nuevo_creyente',
            field=models.BooleanField(default=False, help_text='Marcar si es un nuevo creyente en proceso de seguimiento (aún no miembro oficial).'),
        ),
    ]
