# Generated by Django 5.2.8 on 2025-12-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0009_miembro_nuevo_creyente'),
    ]

    operations = [
      migrations.AddField(
    model_name='miembro',
    name='numero_miembro',
    field=models.PositiveIntegerField(
        blank=True,
        help_text='Número interno autogenerado para el miembro.',
        null=True,
        unique=True,
    ),
),

    ]
