# Generated by Django 5.2.8 on 2025-12-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0011_alter_miembro_codigo_miembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='codigo_miembro',
            field=models.CharField(blank=True, help_text='Código final del miembro con prefijo, ej: TF-0001.', max_length=50, null=True, unique=True),
        ),
    ]
