# Generated by Django 5.2.8 on 2025-12-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0012_miembro_codigo_miembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='numero_seguimiento',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
