# Generated by Django 5.2.8 on 2026-01-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0013_miembro_codigo_seguimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembrorelacion',
            name='tipo_relacion',
            field=models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('hijo', 'Hijo/a'), ('conyuge', 'Cónyuge'), ('hermano', 'Hermano/a'), ('abuelo', 'Abuelo/Abuela'), ('nieto', 'Nieto/Nieta'), ('tio', 'Tío/Tía'), ('sobrino', 'Sobrino/Sobrina'), ('primo', 'Primo/Prima'), ('suegro', 'Suegro/Suegra'), ('yerno', 'Yerno/Nuera'), ('cunado', 'Cuñado/Cuñada'), ('tutor', 'Tutor/a'), ('otro', 'Otro')], max_length=20),
        ),
    ]
