# Generated by Django 5.2.8 on 2026-01-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0014_alter_miembrorelacion_tipo_relacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='situacion_economica',
            field=models.CharField(blank=True, choices=[('estable', 'Estable'), ('vulnerable', 'Vulnerable'), ('critica', 'Crítica')], help_text='Evaluación general (uso interno/pastoral).', max_length=20),
        ),
        migrations.AddField(
            model_name='miembro',
            name='tiene_vehiculo',
            field=models.BooleanField(default=False, help_text='Marcar si el miembro posee vehículo.'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='tipo_vivienda',
            field=models.CharField(blank=True, choices=[('propia', 'Casa propia'), ('alquilada', 'Alquilada'), ('familiar', 'En casa de familiares'), ('prestada', 'Prestada / Cedida')], help_text='Tipo de vivienda donde reside el miembro.', max_length=20),
        ),
        migrations.AddField(
            model_name='miembro',
            name='vehiculo_marca',
            field=models.CharField(blank=True, help_text='Marca del vehículo (si aplica).', max_length=50),
        ),
        migrations.AddField(
            model_name='miembro',
            name='vehiculo_placa',
            field=models.CharField(blank=True, help_text='Placa (si aplica).', max_length=20),
        ),
        migrations.AddField(
            model_name='miembro',
            name='vehiculo_tipo',
            field=models.CharField(blank=True, choices=[('carro', 'Carro'), ('jeepeta', 'Jeepeta'), ('camioneta', 'Camioneta'), ('motor', 'Motor'), ('camion', 'Camión'), ('otro', 'Otro')], help_text='Tipo de vehículo (si aplica).', max_length=20),
        ),
    ]
