# Generated by Django 5.2.8 on 2026-01-05 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0015_miembro_situacion_economica_miembro_tiene_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='telefono',
            field=models.CharField(blank=True, help_text='Ej: +1 809 123 4567', max_length=20, validators=[django.core.validators.RegexValidator(message='Formato válido: +1 809 123 4567', regex='^\\+1\\s?(809|829|849)\\s?\\d{3}\\s?\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Ej: +1 829 123 4567', max_length=20, validators=[django.core.validators.RegexValidator(message='Formato válido: +1 809 123 4567', regex='^\\+1\\s?(809|829|849)\\s?\\d{3}\\s?\\d{4}$')]),
        ),
    ]
