# Generated by Django 5.2.8 on 2026-01-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0016_alter_miembro_telefono_alter_miembro_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
