# Generated by Django 5.2.8 on 2026-01-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0017_alter_miembro_telefono_alter_miembro_whatsapp'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='miembro',
            constraint=models.UniqueConstraint(condition=models.Q(('cedula__isnull', False)), fields=('cedula',), name='unique_cedula_miembro'),
        ),
    ]
