# Generated by Django 5.2.8 on 2026-01-11 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0018_miembro_unique_cedula_miembro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuario del sistema vinculado a este miembro (si aplica).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembro', to=settings.AUTH_USER_MODEL),
        ),
    ]
