# Generated by Django 5.2.8 on 2026-01-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0019_miembro_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='razonsalidamiembro',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Razón de salida', 'verbose_name_plural': 'Razones de salida'},
        ),
        migrations.AddField(
            model_name='razonsalidamiembro',
            name='aplica_a',
            field=models.CharField(choices=[('miembro', 'Miembro'), ('nuevo_creyente', 'Nuevo creyente'), ('ambos', 'Ambos')], default='ambos', help_text='Define si esta razón aplica a miembros, nuevos creyentes o ambos.', max_length=20),
        ),
        migrations.AlterField(
            model_name='razonsalidamiembro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='razonsalidamiembro',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='razonsalidamiembro',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='razonsalidamiembro',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
