# Generated by Django 5.2.8 on 2026-01-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0020_alter_razonsalidamiembro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='razonsalidamiembro',
            name='permite_carta',
            field=models.BooleanField(default=False, help_text='Permite generar/enviar carta de salida (ej: Trasladado, Otra iglesia).'),
        ),
    ]
