# Generated by Django 5.2.8 on 2026-01-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0021_razonsalidamiembro_permite_carta'),
    ]

    operations = [
        migrations.AddField(
            model_name='razonsalidamiembro',
            name='carta_traslado_recibida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='razonsalidamiembro',
            name='estado_pastoral_reingreso',
            field=models.CharField(blank=True, choices=[('reconciliado', 'Reconciliado'), ('restituido', 'Restituido'), ('observacion', 'En observación')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='razonsalidamiembro',
            name='etapa_actual',
            field=models.CharField(choices=[('miembro', 'Miembro'), ('nuevo_creyente', 'Nuevo creyente'), ('reincorporado', 'Reincorporado'), ('inactivo', 'Inactivo')], db_index=True, default='miembro', max_length=20),
        ),
        migrations.AddField(
            model_name='razonsalidamiembro',
            name='fecha_reingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='razonsalidamiembro',
            name='nota_pastoral_reingreso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='razonsalidamiembro',
            name='origen_reingreso',
            field=models.CharField(blank=True, choices=[('descarriado', 'Descarriado'), ('traslado', 'Traslado'), ('pausa', 'Pausa voluntaria')], max_length=20, null=True),
        ),
    ]
