# Generated by Django 5.2.8 on 2026-01-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0023_remove_razonsalidamiembro_carta_traslado_recibida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='razonsalidamiembro',
            name='estado_resultante',
            field=models.CharField(blank=True, choices=[('', '—'), ('descarriado', 'Descarriado'), ('trasladado', 'Trasladado')], default='', help_text='Al dar salida, este será el estado_miembro que quedará marcado (ej: descarriado/trasladado).', max_length=20),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado_miembro',
            field=models.CharField(blank=True, choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('observacion', 'En observación'), ('disciplina', 'En disciplina'), ('descarriado', 'Descarriado'), ('catecumeno', 'Catecúmeno'), ('trasladado', 'Trasladado')], help_text='Estado pastoral del miembro (activo, pasivo, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='estado_pastoral_reingreso',
            field=models.CharField(blank=True, choices=[('reconciliado', 'Reconciliado'), ('integrado', 'Integrado (viene de otra iglesia)'), ('observacion', 'En observación')], max_length=20, null=True),
        ),
    ]
