# Generated by Django 5.2.8 on 2026-01-15 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0024_razonsalidamiembro_estado_resultante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='fecha_ingreso_iglesia',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Fecha en que empezó a congregarse en la iglesia.'),
        ),
    ]
