# Generated by Django 5.2.8 on 2026-01-15 02:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0025_alter_miembro_fecha_ingreso_iglesia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sistema', 'Sistema'), ('salida', 'Salida'), ('reingreso', 'Reincorporación'), ('cambio_estado', 'Cambio de estado'), ('cambio_etapa', 'Cambio de etapa'), ('nota', 'Nota'), ('documento', 'Documento')], default='sistema', max_length=30)),
                ('titulo', models.CharField(max_length=140)),
                ('detalle', models.TextField(blank=True, default='')),
                ('estado_from', models.CharField(blank=True, default='', max_length=40)),
                ('estado_to', models.CharField(blank=True, default='', max_length=40)),
                ('etapa_from', models.CharField(blank=True, default='', max_length=40)),
                ('etapa_to', models.CharField(blank=True, default='', max_length=40)),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miembro_bitacoras', to=settings.AUTH_USER_MODEL)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='miembros_app.miembro')),
            ],
            options={
                'verbose_name': 'Bitácora (Miembro)',
                'verbose_name_plural': 'Bitácoras (Miembro)',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
