# Generated by Django 5.2.8 on 2026-01-15 17:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0027_miembro_telefono_norm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('creacion', 'Creación'), ('edicion', 'Edición de datos'), ('estado', 'Cambio de estado'), ('etapa', 'Cambio de etapa'), ('bautismo', 'Bautismo'), ('unidad_asignada', 'Asignación a unidad'), ('unidad_removida', 'Remoción de unidad'), ('email', 'Envío de correo'), ('baja', 'Baja'), ('reingreso', 'Reingreso'), ('foto', 'Cambio de foto'), ('relacion', 'Relación familiar'), ('otro', 'Otro')], db_index=True, default='otro', max_length=20)),
                ('descripcion', models.CharField(help_text='Descripción corta del evento', max_length=255)),
                ('detalle', models.TextField(blank=True, default='', help_text='Información adicional del evento (opcional)')),
                ('valor_anterior', models.CharField(blank=True, default='', max_length=100)),
                ('valor_nuevo', models.CharField(blank=True, default='', max_length=100)),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('referencia_tipo', models.CharField(blank=True, default='', max_length=50)),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento de Timeline',
                'verbose_name_plural': 'Eventos de Timeline',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='miembro',
            name='miembros_te_norm_idx',
        ),
        migrations.AlterField(
            model_name='miembro',
            name='telefono_norm',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='miembros_app.miembro'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['miembro', '-fecha'], name='miembros_ap_miembro_0ce784_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['tipo', '-fecha'], name='miembros_ap_tipo_b45e4d_idx'),
        ),
    ]
