# Generated by Django 5.2.8 on 2026-01-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0028_timelineevent_remove_miembro_miembros_te_norm_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaGeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('provincia', models.CharField(blank=True, default='', max_length=100)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zona (Geo)',
                'verbose_name_plural': 'Zonas (Geo)',
                'ordering': ['provincia', 'ciudad', 'sector'],
                'unique_together': {('sector', 'ciudad', 'provincia')},
            },
        ),
    ]
