# Generated by Django 5.2.8 on 2026-01-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0029_zonageo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonageo',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('Higuey', 'Higüey'), ('Punta Cana', 'Punta Cana'), ('San Rafael del Yuma', 'San Rafael del Yuma')], default='Higuey', max_length=50),
        ),
        migrations.AlterField(
            model_name='zonageo',
            name='provincia',
            field=models.CharField(blank=True, choices=[('La Altagracia', 'La Altagracia')], default='La Altagracia', max_length=50),
        ),
    ]
