# Generated by Django 5.2.8 on 2026-01-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0030_alter_zonageo_ciudad_alter_zonageo_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('Higuey', 'Higüey'), ('Punta Cana', 'Punta Cana'), ('San Rafael del Yuma', 'San Rafael del Yuma')], max_length=100),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='provincia',
            field=models.CharField(blank=True, choices=[('La Altagracia', 'La Altagracia')], max_length=100),
        ),
    ]
