# Generated by Django 5.2.8 on 2026-01-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0031_alter_miembro_ciudad_alter_miembro_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='padres_espirituales',
            field=models.ManyToManyField(blank=True, related_name='hijos_espirituales', to='miembros_app.miembro', verbose_name='Padres espirituales'),
        ),
    ]
