# Generated by Django 5.2.8 on 2026-01-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0032_miembro_padres_espirituales'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='bautizado_espiritu_santo',
            field=models.BooleanField(default=False, help_text='Indica si está bautizado en el Espíritu Santo.'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='donde_estudio_teologia',
            field=models.CharField(blank=True, default='', help_text='Institución / lugar donde estudió teología (si aplica).', max_length=255),
        ),
        migrations.AddField(
            model_name='miembro',
            name='mision_ciudad',
            field=models.CharField(blank=True, default='', help_text='Ciudad donde sirve como misionero (si aplica).', max_length=100),
        ),
        migrations.AddField(
            model_name='miembro',
            name='mision_pais',
            field=models.CharField(blank=True, default='', help_text='País donde sirve como misionero (si aplica).', max_length=100),
        ),
        migrations.AddField(
            model_name='miembro',
            name='misionero_activo',
            field=models.BooleanField(default=False, help_text='Marca si actualmente está activo como misionero.'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='obrero_ordenado',
            field=models.BooleanField(default=False, help_text='Indica si es obrero ordenado.'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='preparacion_teologica',
            field=models.CharField(blank=True, default='', help_text='Resumen breve de la preparación teológica (si aplica).', max_length=255),
        ),
        migrations.AddField(
            model_name='miembro',
            name='rol_ministerial',
            field=models.CharField(blank=True, choices=[('', '—'), ('pastor', 'Pastor'), ('evangelista', 'Evangelista'), ('misionero', 'Misionero'), ('obrero', 'Obrero')], default='', help_text='Rol ministerial (si aplica).', max_length=20),
        ),
        migrations.AddField(
            model_name='miembro',
            name='tiene_credenciales',
            field=models.BooleanField(default=False, help_text='Indica si posee credenciales ministeriales.'),
        ),
    ]
