# Generated by Django 5.2.8 on 2026-01-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0033_miembro_bautizado_espiritu_santo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='area_formacion',
            field=models.CharField(blank=True, choices=[('', '—'), ('pastoral', 'Pastoral'), ('biblica', 'Bíblica'), ('misionologia', 'Misionología'), ('consejeria', 'Consejería'), ('educacion_cristiana', 'Educación Cristiana'), ('otra', 'Otra')], default='', help_text='Área principal de formación.', max_length=30),
        ),
        migrations.AddField(
            model_name='miembro',
            name='credencial_fecha_emision',
            field=models.DateField(blank=True, help_text='Fecha de emisión de la credencial.', null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='credencial_fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento de la credencial (si aplica).', null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='cursos_certificaciones',
            field=models.TextField(blank=True, help_text='Cursos, diplomados o certificaciones relevantes.'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='estado_ministerial',
            field=models.CharField(blank=True, choices=[('', '—'), ('activo', 'Activo'), ('pausa', 'En pausa'), ('retirado', 'Retirado')], default='', help_text='Estado actual en el ministerio.', max_length=20),
        ),
        migrations.AddField(
            model_name='miembro',
            name='mision_fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha de fin de la misión (si aplica).', null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='mision_fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio de la misión.', null=True),
        ),
        migrations.AddField(
            model_name='miembro',
            name='mision_tipo',
            field=models.CharField(blank=True, choices=[('', '—'), ('permanente', 'Permanente'), ('temporal', 'Temporal'), ('viajes', 'Viajes misioneros')], default='', help_text='Tipo de misión realizada.', max_length=20),
        ),
        migrations.AddField(
            model_name='miembro',
            name='nivel_formacion',
            field=models.CharField(blank=True, choices=[('', '—'), ('basica', 'Básica'), ('tecnica', 'Técnica'), ('diplomado', 'Diplomado'), ('licenciatura', 'Licenciatura'), ('otro', 'Otro')], default='', help_text='Nivel de formación teológica.', max_length=20),
        ),
        migrations.AddField(
            model_name='miembro',
            name='numero_credencial',
            field=models.CharField(blank=True, help_text='Número o código de la credencial ministerial.', max_length=60),
        ),
    ]
