# Generated by Django 5.2.8 on 2026-01-26 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0034_miembro_area_formacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HogarFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hogares', to='miembros_app.clanfamiliar')),
            ],
        ),
        migrations.CreateModel(
            name='HogarMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('padre', 'Padre'), ('madre', 'Madre'), ('hijo', 'Hijo/Hija'), ('otro', 'Otro')], max_length=20)),
                ('es_principal', models.BooleanField(default=False)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='miembros_app.hogarfamiliar')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hogares', to='miembros_app.miembro')),
            ],
            options={
                'unique_together': {('hogar', 'miembro')},
            },
        ),
    ]
