# Generated by Django 5.2.8 on 2026-01-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0035_clanfamiliar_hogarfamiliar_hogarmiembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembrorelacion',
            name='es_inferida',
            field=models.BooleanField(default=False, help_text='True si fue creada automáticamente por el sistema.'),
        ),
    ]
