# Generated by Django 5.2.8 on 2026-02-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0036_miembrorelacion_es_inferida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='estado_miembro',
            field=models.CharField(blank=True, choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('observacion', 'En observación'), ('disciplina', 'En disciplina'), ('descarriado', 'Descarriado'), ('catecumeno', 'Catecúmeno'), ('trasladado', 'Trasladado'), ('fallecido', 'Fallecido')], help_text='Estado pastoral del miembro (activo, pasivo, etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='razonsalidamiembro',
            name='estado_resultante',
            field=models.CharField(blank=True, choices=[('', '—'), ('descarriado', 'Descarriado'), ('trasladado', 'Trasladado'), ('fallecido', 'Fallecido')], default='', help_text='Al dar salida, este será el estado_miembro que quedará marcado (ej: descarriado/trasladado).', max_length=20),
        ),
    ]
