# Generated by Django 5.2.8 on 2026-03-03 01:52

import django.db.models.deletion
from django.db import migrations, models


def create_default_tenant(apps, schema_editor):
    Tenant = apps.get_model('tenants', 'Tenant')
    Tenant.objects.get_or_create(id=1, defaults={'nombre': 'Torre Fuerte'})


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0037_alter_miembro_estado_miembro_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        # Primero crear el tenant
        migrations.RunPython(create_default_tenant, migrations.RunPython.noop),
        # Luego agregar el campo
        migrations.AddField(
            model_name='miembro',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
            preserve_default=False,
        ),
    ]