# Generated by Django 5.2.8 on 2026-03-03 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0038_miembro_tenant'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='miembro',
            name='unique_cedula_miembro',
        ),
        migrations.AddField(
            model_name='clanfamiliar',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hogarfamiliar',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miembrobitacora',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miembrorelacion',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='razonsalidamiembro',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='miembro',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si está desmarcado, el miembro ya no pertenece a la iglesia.'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='codigo_miembro',
            field=models.CharField(blank=True, help_text='Código final del miembro con prefijo, ej: TF-0001.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='fecha_salida',
            field=models.DateField(blank=True, help_text='Fecha en que dejó de pertenecer a la iglesia.', null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='numero_miembro',
            field=models.PositiveIntegerField(blank=True, help_text='Número interno autogenerado para el miembro.', null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='numero_seguimiento',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='razonsalidamiembro',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='miembro',
            constraint=models.UniqueConstraint(condition=models.Q(('cedula__isnull', False), models.Q(('cedula', ''), _negated=True)), fields=('tenant', 'cedula'), name='unique_cedula_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='miembro',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_miembro__isnull', False)), fields=('tenant', 'codigo_miembro'), name='unique_codigo_miembro_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='miembro',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_seguimiento__isnull', False)), fields=('tenant', 'codigo_seguimiento'), name='unique_codigo_seguimiento_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='miembro',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_miembro__isnull', False)), fields=('tenant', 'numero_miembro'), name='unique_numero_miembro_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='miembro',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_seguimiento__isnull', False)), fields=('tenant', 'numero_seguimiento'), name='unique_numero_seguimiento_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='razonsalidamiembro',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='unique_razon_salida_por_tenant'),
        ),
    ]
