# Generated by Django 5.2.8 on 2026-03-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0039_remove_miembro_unique_cedula_miembro_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='miembrorelacion',
            constraint=models.UniqueConstraint(fields=('tenant', 'miembro', 'familiar', 'tipo_relacion'), name='unique_relacion_por_tenant'),
        ),
    ]
