# Generated by Django 5.2.8 on 2026-03-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0040_miembrorelacion_unique_relacion_por_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='apodo',
            field=models.CharField(blank=True, help_text='Nombre por el cual se le conoce comúnmente.', max_length=50, verbose_name='Apodo'),
        ),
    ]
