# Generated by Django 5.2.8 on 2025-12-03 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miembros_app', '0012_miembro_codigo_miembro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ejemplo: 'Elección de diáconos 2026'.", max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la votación.')),
                ('tipo', models.CharField(choices=[('DIACONOS', 'Diáconos'), ('LIDERES', 'Líderes'), ('JUNTA', 'Junta directiva'), ('MINISTERIOS', 'Ministerios'), ('ESPECIAL', 'Votación especial'), ('ENCUESTA', 'Encuesta')], default='DIACONOS', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ABIERTA', 'Abierta para votar'), ('CERRADA', 'Cerrada')], default='BORRADOR', help_text='Controla si la votación está abierta en el modo kiosko.', max_length=10)),
                ('total_habilitados', models.PositiveIntegerField(blank=True, help_text='Número total de personas con derecho a voto para esta elección.', null=True)),
                ('quorum_minimo', models.PositiveIntegerField(blank=True, help_text='Número mínimo de votantes requeridos (quórum). Opcional.', null=True)),
                ('regla_ganador', models.CharField(choices=[('MAYORIA_50_1', 'Mayoría 50% + 1'), ('MAS_VOTOS', 'Más votos (simple)'), ('TOP_N', 'Top N más votados'), ('TOP_1_Y_2', '1er y 2do lugar')], default='MAYORIA_50_1', help_text='Regla que define cómo se escogen los ganadores.', max_length=20)),
                ('numero_cargos', models.PositiveIntegerField(blank=True, help_text='Cantidad de cargos a elegir (ej. 3 diáconos, 2 líderes, etc.).', null=True)),
                ('permite_empates', models.BooleanField(default=True, help_text='Si está desmarcado, luego se deberá gestionar el desempate.')),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha/hora en la que se abre la votación (opcional).', null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha/hora en la que se cierra la votación (opcional).', null=True)),
                ('permite_voto_remoto', models.BooleanField(default=False, help_text='Si está activo, se podrá habilitar voto remoto en el futuro.')),
                ('observaciones_internas', models.TextField(blank=True, help_text='Notas internas para el comité de votación (no se muestran al público).')),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('actualizada_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Votación',
                'verbose_name_plural': 'Votaciones',
                'ordering': ['-creada_el'],
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del candidato.', max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Información adicional del candidato (opcional).')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en que aparecerá en la lista (0 = sin orden específico).')),
                ('activo', models.BooleanField(default=True, help_text='Si está desmarcado, el candidato no se muestra para votar.')),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='votacion_app.votacion')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablet_id', models.CharField(blank=True, help_text='Identificador de la tablet o dispositivo (opcional).', max_length=50)),
                ('emitido_el', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='votacion_app.candidato')),
                ('miembro', models.ForeignKey(help_text='Miembro que emitió el voto.', on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='miembros_app.miembro')),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='votacion_app.votacion')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'ordering': ['-emitido_el'],
                'constraints': [models.UniqueConstraint(fields=('votacion', 'miembro'), name='un_voto_por_miembro_y_votacion')],
            },
        ),
    ]
