# Generated by Django 5.2.8 on 2025-12-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0012_miembro_codigo_miembro'),
        ('votacion_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ronda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1, help_text='1 = primera vuelta, 2 = segunda vuelta, etc.')),
                ('nombre', models.CharField(blank=True, help_text="Nombre opcional de la vuelta (ej.: 'Primera vuelta').", max_length=150)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ABIERTA', 'Abierta para votar'), ('CERRADA', 'Cerrada')], default='BORRADOR', max_length=10)),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha/hora real de inicio de esta vuelta (opcional).', null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha/hora real de cierre de esta vuelta (opcional).', null=True)),
            ],
            options={
                'verbose_name': 'Vuelta',
                'verbose_name_plural': 'Vueltas',
                'ordering': ['numero'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='voto',
            name='un_voto_por_miembro_y_votacion',
        ),
        migrations.AlterField(
            model_name='votacion',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora de referencia de cierre (opcional).', null=True),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora de referencia para la votación (opcional).', null=True),
        ),
        migrations.AddField(
            model_name='ronda',
            name='votacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rondas', to='votacion_app.votacion'),
        ),
        migrations.AddField(
            model_name='voto',
            name='ronda',
            field=models.ForeignKey(blank=True, help_text='Vuelta en la que se emitió este voto.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votos', to='votacion_app.ronda'),
        ),
        migrations.AddConstraint(
            model_name='voto',
            constraint=models.UniqueConstraint(fields=('ronda', 'miembro'), name='un_voto_por_miembro_y_ronda'),
        ),
    ]
