# Generated by Django 5.2.8 on 2025-12-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion_app', '0002_ronda_remove_voto_un_voto_por_miembro_y_votacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacion',
            name='edad_minima_candidato',
            field=models.PositiveIntegerField(blank=True, help_text='Edad mínima para ser candidato en esta elección (ej. 18 años).', null=True),
        ),
    ]
