# Generated by Django 5.2.8 on 2025-12-04 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0012_miembro_codigo_miembro'),
        ('votacion_app', '0003_votacion_edad_minima_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='miembro',
            field=models.ForeignKey(blank=True, help_text='Miembro que es candidato en esta elección.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidaturas', to='miembros_app.miembro'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nombre',
            field=models.CharField(help_text='Nombre del candidato (se puede rellenar automáticamente desde el miembro).', max_length=150),
        ),
    ]
