# Generated by Django 5.2.8 on 2025-12-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion_app', '0004_candidato_miembro_alter_candidato_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votacion',
            name='quorum_minimo',
        ),
        migrations.AddField(
            model_name='votacion',
            name='miembros_presentes',
            field=models.PositiveIntegerField(blank=True, help_text='Número de miembros con derecho a voto que están presentes físicamente.', null=True),
        ),
        migrations.AddField(
            model_name='votacion',
            name='tipo_quorum',
            field=models.CharField(choices=[('PORCENTAJE', 'Porcentaje de presentes'), ('CANTIDAD', 'Cantidad fija de personas')], default='PORCENTAJE', help_text='Define si el quórum se calcula por porcentaje o por cantidad fija.', max_length=20),
        ),
        migrations.AddField(
            model_name='votacion',
            name='valor_quorum',
            field=models.PositiveIntegerField(blank=True, help_text='Si el quórum es porcentual, representa el porcentaje (ej. 50). Si es cantidad, el número de personas.', null=True),
        ),
        migrations.AddField(
            model_name='votacion',
            name='votos_minimos_requeridos',
            field=models.PositiveIntegerField(blank=True, help_text='Número de votos mínimos requeridos para que la votación sea válida.', null=True),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='regla_ganador',
            field=models.CharField(choices=[('LA1', 'La 1 · Mayoría absoluta secuencial (50% + 1)'), ('LA2', 'La 2 · Mayoría adaptativa (umbral recalculado)'), ('LA3', 'La 3 · Mayoría 50%+1 y los demás por orden de votos'), ('LA4', 'La 4 · TOP N (los más votados)'), ('LA5', 'La 5 · Segunda vuelta (dos más votados)'), ('LA6', 'La 6 · Mayoría especial (2/3 o 3/4)')], default='LA1', help_text='Regla que define cómo se escogen los ganadores.', max_length=20),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='total_habilitados',
            field=models.PositiveIntegerField(blank=True, help_text='Miembros con derecho a voto para esta elección (calculado automáticamente).', null=True),
        ),
    ]
