# Generated by Django 5.2.8 on 2025-12-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion_app', '0005_remove_votacion_quorum_minimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacion',
            name='base_quorum',
            field=models.CharField(choices=[('HABILITADOS', 'Sobre total de habilitados'), ('PRESENTES', 'Sobre miembros presentes')], default='HABILITADOS', help_text='Indica si el quórum se calcula usando el total de habilitados o solo los presentes.', max_length=20),
        ),
        migrations.AlterField(
            model_name='votacion',
            name='tipo_quorum',
            field=models.CharField(choices=[('PORCENTAJE', 'Porcentaje sobre la base'), ('CANTIDAD', 'Cantidad fija de personas')], default='PORCENTAJE', help_text='Define si el quórum se calcula por porcentaje o por cantidad fija sobre la base elegida.', max_length=20),
        ),
    ]
