# Generated by Django 5.2.8 on 2025-12-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion_app', '0006_votacion_base_quorum_alter_votacion_tipo_quorum'),
    ]

    operations = [
        migrations.AddField(
            model_name='votacion',
            name='mostrar_conteo_en_vivo',
            field=models.BooleanField(default=False, help_text='Si está marcado, la pantalla pública mostrará el conteo de votos en tiempo real mientras la votación esté ABIERTA. Si no, solo se verán los candidatos y los resultados aparecerán cuando la votación se cierre.'),
        ),
    ]
