# Generated by Django 5.2.8 on 2025-12-06 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros_app', '0012_miembro_codigo_miembro'),
        ('votacion_app', '0007_votacion_mostrar_conteo_en_vivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCandidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre de la lista, por ejemplo: 'Propuesta diáconos 2026'.", max_length=150)),
                ('codigo_lista', models.CharField(blank=True, help_text='Código opcional para identificar la lista (ej. LD-2026-01).', max_length=30, null=True, unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada')], default='BORRADOR', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre esta lista (visible solo en el sistema).')),
            ],
            options={
                'verbose_name': 'Lista de candidatos',
                'verbose_name_plural': 'Listas de candidatos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ListaCandidatosItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden opcional para mostrar esta lista.')),
                ('observacion', models.CharField(blank=True, help_text='Observación opcional sobre este candidato en esta lista.', max_length=200)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='votacion_app.listacandidatos')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas_candidatos', to='miembros_app.miembro')),
            ],
            options={
                'verbose_name': 'Elemento de lista de candidatos',
                'verbose_name_plural': 'Elementos de listas de candidatos',
                'ordering': ['orden', 'miembro__apellidos', 'miembro__nombres'],
                'unique_together': {('lista', 'miembro')},
            },
        ),
    ]
