# Generated by Django 5.2.8 on 2026-03-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('visita', 'Visita'), ('amigo', 'Amigo')], default='visita', max_length=20)),
                ('fecha_visita', models.DateField()),
                ('primera_vez', models.BooleanField(default=True)),
                ('invitado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('desea_contacto', models.BooleanField(default=True)),
                ('peticion_oracion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('seguimiento', 'En seguimiento'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-fecha_visita', '-id'],
            },
        ),
    ]
