# Generated by Django 5.2.8 on 2026-03-12 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-fecha_ultima_visita', '-id'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.RenameField(
            model_name='visita',
            old_name='fecha_visita',
            new_name='fecha_primera_visita',
        ),
        migrations.AddField(
            model_name='visita',
            name='cantidad_visitas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='visita',
            name='fecha_ultima_visita',
            field=models.DateField(default=datetime.date(2026, 3, 12)),
            preserve_default=False,
        ),
    ]
