# Generated by Django 5.2.8 on 2026-03-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_app', '0002_alter_visita_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
    ]
