# Generated by Django 5.2.8 on 2026-03-12 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_app', '0003_visita_edad_visita_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Clasificación de visita',
                'verbose_name_plural': 'Clasificaciones de visitas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='visita',
            name='tipo',
        ),
        migrations.AddField(
            model_name='visita',
            name='clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitas', to='visitas_app.clasificacionvisita'),
        ),
    ]
