# Generated by Django 5.2.8 on 2026-03-12 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('visitas_app', '0004_clasificacionvisita_remove_visita_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacionvisita',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visita',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clasificacionvisita',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visita',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='clasificacionvisita',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='uniq_clasificacion_visita_nombre_por_tenant'),
        ),
    ]
