# Generated by Django 5.2.8 on 2026-03-12 19:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0017_unidad_hereda_liderazgo'),
        ('tenants', '0001_initial'),
        ('visitas_app', '0005_clasificacionvisita_tenant_visita_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRegistroVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de registro de visita',
                'verbose_name_plural': 'Tipos de registros de visitas',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha_primera_visita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha_ultima_visita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegistroVisitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant')),
                ('unidad_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_visitas', to='estructura_app.unidad')),
            ],
            options={
                'verbose_name': 'Registro de visitas',
                'verbose_name_plural': 'Registros de visitas',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='visita',
            name='registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='visitas_app.registrovisitas'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['registro'], name='visitas_app_registr_813c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['estado'], name='visitas_app_estado_5009cc_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['telefono'], name='visitas_app_telefon_e5b92e_idx'),
        ),
        migrations.AddField(
            model_name='tiporegistrovisita',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='registrovisitas',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='visitas_app.tiporegistrovisita'),
        ),
        migrations.AddConstraint(
            model_name='tiporegistrovisita',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='uniq_tipo_registro_visita_nombre_por_tenant'),
        ),
        migrations.AddIndex(
            model_name='registrovisitas',
            index=models.Index(fields=['fecha'], name='visitas_app_fecha_2ee95d_idx'),
        ),
        migrations.AddIndex(
            model_name='registrovisitas',
            index=models.Index(fields=['tipo'], name='visitas_app_tipo_id_d43f0d_idx'),
        ),
    ]
