# Generated by Django 5.2.8 on 2026-03-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estructura_app', '0017_unidad_hereda_liderazgo'),
        ('tenants', '0001_initial'),
        ('visitas_app', '0006_tiporegistrovisita_alter_visita_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovisitas',
            name='cerrado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrovisitas',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20),
        ),
        migrations.AddIndex(
            model_name='registrovisitas',
            index=models.Index(fields=['estado'], name='visitas_app_estado_51dc09_idx'),
        ),
    ]
