# Generated by Django 5.2.8 on 2026-03-21 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas_app', '0007_registrovisitas_cerrado_at_registrovisitas_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovisitas',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_visitas_cerrados', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por'),
        ),
        migrations.AddField(
            model_name='registrovisitas',
            name='reabierto_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reapertura'),
        ),
        migrations.AddField(
            model_name='registrovisitas',
            name='reabierto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_visitas_reabiertos', to=settings.AUTH_USER_MODEL, verbose_name='Reabierto por'),
        ),
        migrations.AlterField(
            model_name='registrovisitas',
            name='cerrado_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cierre'),
        ),
    ]
