# Generated by Django 5.2.8 on 2026-01-20 03:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Categoría de recurso',
                'verbose_name_plural': 'Categorías de recursos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('cantidad_total', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En uso'), ('PRESTADO', 'Prestado'), ('EN_REPARACION', 'En reparación'), ('DANADO', 'Dañado'), ('BAJA', 'Baja')], default='DISPONIBLE', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='inventario/recursos/')),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='inventario_app.categoriarecurso')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='inventario_app.ubicacion')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['nombre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRASLADO', 'Traslado'), ('REPARACION', 'Enviado a reparación'), ('BAJA', 'Baja')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('notas', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario_app.recurso')),
                ('ubicacion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='inventario_app.ubicacion')),
                ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='inventario_app.ubicacion')),
            ],
            options={
                'verbose_name': 'Movimiento de recurso',
                'verbose_name_plural': 'Movimientos de recursos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='recurso',
            index=models.Index(fields=['codigo'], name='inventario__codigo_6c29de_idx'),
        ),
        migrations.AddIndex(
            model_name='recurso',
            index=models.Index(fields=['estado'], name='inventario__estado_8fc611_idx'),
        ),
    ]
