# Generated by Django 5.2.8 on 2026-01-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriarecurso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
