# Generated by Django 5.2.8 on 2026-01-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0002_categoriarecurso_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='condicion_fisica',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], default='BUENO', max_length=20),
        ),
        migrations.AddField(
            model_name='recurso',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='es_consumible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurso',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='garantia_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='marca',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='recurso',
            name='modelo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='recurso',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='recurso',
            name='proveedor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='recurso',
            name='requiere_mantenimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='recurso',
            index=models.Index(fields=['numero_serie'], name='inventario__numero__b3e00d_idx'),
        ),
        migrations.AddIndex(
            model_name='recurso',
            index=models.Index(fields=['condicion_fisica'], name='inventario__condici_23d569_idx'),
        ),
    ]
