# Generated by Django 5.2.8 on 2026-01-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0003_recurso_condicion_fisica_recurso_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='deprecia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurso',
            name='fecha_inicio_depreciacion',
            field=models.DateField(blank=True, help_text='Si está vacío, se usa fecha_compra', null=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='metodo_depreciacion',
            field=models.CharField(choices=[('LINEA_RECTA', 'Línea recta')], default='LINEA_RECTA', max_length=20),
        ),
        migrations.AddField(
            model_name='recurso',
            name='valor_residual_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor al final de la vida útil', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='vida_util_anios',
            field=models.PositiveIntegerField(blank=True, help_text='Ej: 3, 5, 10', null=True),
        ),
    ]
